import type { CivicProject } from "../civic-projects.ts"

export const bsrpCorridor2MalligeLine: CivicProject = {
  slug: "bsrp-corridor-2-mallige-line",
  cityId: "bengaluru",
  title: "Bengaluru Suburban Rail Corridor 2 (Mallige Line)",
  shortTitle: "Mallige Line (suburban rail)",
  routeName: "Baiyappanahalli to Chikkabanavara",
  projectType: "Suburban rail corridor",
  road: "Suburban Rail Corridor 2",
  status: "Delayed",
  statusNote: "L&T terminated its Corridor 2 civil contract in July 2025, and the remaining work was re-tendered. K-RIDE now targets first services by December 2028; the project deadline was separately reported as extended to March 2030.",
  ownerAgency: "Rail Infrastructure Development Company (Karnataka) Limited (K-RIDE)",
  ownerAgencyShort: "K-RIDE",
  nextTarget: "Dec 2028",
  wardSignalNote: "K-RIDE · civil contract terminated 2025 · first services targeted Dec 2028",
  affectedWards: [
    { corporationId: 1, corporation: "Central", wardNo: 12, name: "Kasturi Nagar" },
    { corporationId: 1, corporation: "Central", wardNo: 13, name: "Krishnaiahnapalya" },
    { corporationId: 2, corporation: "North", wardNo: 11, name: "Doddabommasandra" },
    { corporationId: 2, corporation: "North", wardNo: 13, name: "Kodigehalli" },
    { corporationId: 2, corporation: "North", wardNo: 18, name: "Kempapura" },
    { corporationId: 2, corporation: "North", wardNo: 22, name: "Nagavara" },
    { corporationId: 2, corporation: "North", wardNo: 24, name: "HBR Layout" },
    { corporationId: 2, corporation: "North", wardNo: 25, name: "Govindapura" },
    { corporationId: 2, corporation: "North", wardNo: 26, name: "Samadhana Nagar" },
    { corporationId: 2, corporation: "North", wardNo: 27, name: "K.G.Halli" },
    { corporationId: 2, corporation: "North", wardNo: 28, name: "Venkateshpuram" },
    { corporationId: 2, corporation: "North", wardNo: 29, name: "Lingarajpura" },
    { corporationId: 2, corporation: "North", wardNo: 35, name: "Kammanahalli" },
    { corporationId: 2, corporation: "North", wardNo: 36, name: "Maruthi Seva Nagara" },
    { corporationId: 2, corporation: "North", wardNo: 38, name: "Shampura" },
    { corporationId: 2, corporation: "North", wardNo: 46, name: "Sagayapuram" },
    { corporationId: 2, corporation: "North", wardNo: 52, name: "Vishwanatha Nagenahalli" },
    { corporationId: 2, corporation: "North", wardNo: 56, name: "Hebbal" },
    { corporationId: 2, corporation: "North", wardNo: 57, name: "Bhoopasandra" },
    { corporationId: 2, corporation: "North", wardNo: 58, name: "Nagashettyhalli" },
    { corporationId: 2, corporation: "North", wardNo: 59, name: "Geddalahalli" },
    { corporationId: 2, corporation: "North", wardNo: 60, name: "Jalahalli" },
    { corporationId: 2, corporation: "North", wardNo: 61, name: "HMT Ward" },
    { corporationId: 2, corporation: "North", wardNo: 62, name: "Brundavana Nagara" },
    { corporationId: 2, corporation: "North", wardNo: 63, name: "J.P PARK" },
    { corporationId: 2, corporation: "North", wardNo: 65, name: "Abbigere" },
    { corporationId: 2, corporation: "North", wardNo: 66, name: "Kammagondanahalli" },
    { corporationId: 2, corporation: "North", wardNo: 67, name: "Shettihalli" },
    { corporationId: 5, corporation: "West", wardNo: 35, name: "Goraguntepalya" },
    { corporationId: 5, corporation: "West", wardNo: 48, name: "Mathikere" },
  ],
  wardBasis: "Wards within 30 m of the alignment as mapped in OpenStreetMap (checked 17 September 2026). Kaun derived this list; the agency does not publish one.",
  aliases: [
    "BSRP",
    "Bengaluru Suburban Rail Project",
    "suburban railway",
    "Mallige",
    "Corridor-2",
    "Larsen & Toubro",
    "Benniganahalli",
    "Baiyappanahalli",
    "Yeshwanthpur",
    "Lottegollahalli",
  ],
  summary: "Corridor 2 (the Mallige Line, 25.01 km) is the only one of Bengaluru's four suburban rail corridors whose land acquisition is complete, according to a July 2026 Lok Sabha answer. Its original civil contractor, Larsen & Toubro, terminated its contract in July 2025; K-RIDE disputes the termination, the claims are in arbitration, and the remaining civil work was re-tendered in three packages. K-RIDE now targets first services by December 2028. The terminated contract's value, milestone schedule and payment history were not found in the public sources reviewed.",
  latestAsOf: "2026-09-16",
  alert: "The terminated civil contract's value, milestones and payments are not public, so neither L&T's ₹505 crore claim nor K-RIDE's ₹57 crore guarantee encashment can be checked against the contract.",
  metrics: [
    {
      label: "Length",
      value: "25.01 km",
      note: "Baiyyappanahalli to Chikkabanavara, per the Railways Minister's Lok Sabha answer of 22 July 2026.",
      evidence: "verified",
    },
    {
      label: "Sanctioned cost (4 corridors)",
      value: "₹15,767 Cr",
      note: "For the whole 148.17 km project, per the same Lok Sabha answer. No corridor-wise break-up is public.",
      evidence: "verified",
    },
    {
      label: "Revised cost (4 corridors)",
      value: "₹23,342 Cr",
      note: "Reported by Moneycontrol in March 2026, citing K-RIDE's managing director. A formal revised sanction was not found in the public sources reviewed.",
      evidence: "reported",
    },
    {
      label: "Original target",
      value: "Oct 2026",
      note: "The completion date cited in a Lok Sabha question of July 2026. Moneycontrol later reported the project deadline extended to March 2030.",
      evidence: "reported",
    },
  ],
  records: [
    {
      id: "cabinet-approval-2020",
      date: "2020-10-07",
      dateLabel: "7 October 2020",
      kind: "start",
      title: "Union Cabinet clears 148-km Bengaluru Suburban Rail Project",
      body: "The Union Cabinet approved the 148-km, four-corridor suburban rail project, including Byappanahalli-Chikkabanavara (Corridor-2), to be executed by K-RIDE, an SPV of the Railway Ministry and the Karnataka government. Approval was reported by sources; no official announcement was made on the day due to the election code of conduct.",
      evidence: "reported",
      sourceIds: ["toi-2020-10"],
    },
    {
      id: "foundation-2022",
      date: "2022-06-01",
      dateLabel: "June 2022",
      kind: "start",
      title: "Prime Minister lays foundation stone",
      body: "Prime Minister Narendra Modi laid the foundation stone / flagged off the project in June 2022.",
      evidence: "reported",
      sourceIds: ["ie-2026-04", "toi-2025-08"],
    },
    {
      id: "lnt-contract-2022",
      date: "2022-08-26",
      dateLabel: "26 August 2022",
      kind: "scope",
      title: "K-RIDE signs Corridor-2 civil works contract with Larsen & Toubro",
      body: "L&T entered the Corridor-2 (Chikkabanavara to Benniganahalli) agreement with K-RIDE on 26 August 2022. The original scheduled completion time was 27 months, later extended to 30 September 2026. The contract value was not stated in the public sources reviewed.",
      evidence: "reported",
      sourceIds: ["hindu-2025-11", "hindubusinessline-2025-08"],
    },
    {
      id: "lnt-halts-work-2025",
      date: "2025-03-01",
      dateLabel: "March 2025",
      kind: "land",
      title: "L&T halts work citing non-availability of land",
      body: "L&T halted work on Corridor-2 and Corridor-4 from around March 2025, saying its machinery and manpower sat idle because K-RIDE had not handed over government and private land, cleared encroachments, or shifted utilities. K-RIDE later maintained that 84% of the Corridor-2 alignment had been made available and blamed L&T for failing to mobilise resources and finalise designs.",
      evidence: "conflicting",
      sourceIds: ["ie-2025-10", "toi-2025-08", "hindubusinessline-2025-08"],
    },
    {
      id: "lnt-termination-2025",
      date: "2025-07-31",
      dateLabel: "31 July 2025",
      kind: "accountability",
      title: "L&T terminates Corridor-2 and Corridor-4 contracts; K-RIDE calls it illegal",
      body: "L&T terminated both contracts on 31 July 2025 (notice dated 28 July 2025), accusing K-RIDE of failing to provide land and work fronts and demanding ₹505 crore in dues for completed work and losses. L&T claimed about 22% of scope was done with 96% of scheduled time elapsed. K-RIDE called the termination 'unilateral' and 'illegal', said the contract did not permit it, and said L&T had made unreasonable demands (contract price revision, converting the EPC contract to an itemised BoQ contract). The claims were referred to an Amicable Settlement Committee.",
      evidence: "conflicting",
      sourceIds: ["hindubusinessline-2025-08", "toi-2025-08", "toi-2026-01"],
    },
    {
      id: "retender-decision-2025",
      date: "2025-10-06",
      dateLabel: "6 October 2025",
      kind: "scope",
      title: "K-RIDE decides to re-tender balance Corridor-2 civil works",
      body: "K-RIDE announced it would invite fresh tenders for the remaining Corridor-2 civil works, on the advice of the Karnataka Advocate General and its tender evaluation committee, while arbitration with L&T continued. The balance works were split into three packages.",
      evidence: "reported",
      sourceIds: ["ie-2025-10"],
    },
    {
      id: "fresh-tenders-2025",
      date: "2025-11-04",
      dateLabel: "4 November 2025",
      kind: "scope",
      title: "Fresh tenders invited for Mallige Line in three packages",
      body: "K-RIDE invited fresh tenders: Package 1 — 7.795-km elevated viaduct between Benniganahalli and Shettihalli plus a 1.20-km double-decker viaduct (flyover at Level 1, BSRP tracks at Level 2) between Lottegollahalli and Yeshwanthpur, with Mathikere and Benniganahalli stations, 24-month deadline; Package 2 — 11.569-km at-grade section between Benniganahalli-Banaswadi and Banaswadi-Hebbal with Nagavara and Kanakanagar station boxes, 18 months; Package 3 — 5.8-km at-grade section between Yeshwanthpur and Chikkabanavara with a 185-metre elevated stretch, 18 months.",
      evidence: "reported",
      sourceIds: ["hindu-2025-11"],
    },
    {
      id: "commercial-court-2026",
      date: "2026-01-09",
      dateLabel: "9 January 2026",
      kind: "court",
      title: "Commercial court dismisses L&T plea to stop bank-guarantee invocation",
      body: "A Bengaluru city commercial court dismissed L&T's plea to restrain K-RIDE from invoking bank guarantees (a ₹28.6 crore mobilisation guarantee and a ₹31.2 crore performance guarantee, pertaining to Corridor-4). The court noted that despite work-front availability L&T could not show progress and had itself terminated the contract unilaterally, gave L&T liberty to approach the arbitral tribunal, and vacated interim protection from 24 January 2026.",
      evidence: "reported",
      sourceIds: ["toi-2026-01"],
    },
    {
      id: "cost-revision-2026",
      date: "2026-03-13",
      dateLabel: "13 March 2026",
      kind: "cost",
      title: "Project cost revised from ₹15,767 crore to ₹23,342 crore",
      body: "K-RIDE MD Lakshman Singh told Moneycontrol the BSRP cost had escalated about 48% to ₹23,342 crore, citing inflation and the switch from a PPP lease model to direct procurement of rolling stock (about ₹4,300 crore). The overall project deadline was extended from October 2026 to March 2030.",
      evidence: "reported",
      sourceIds: ["moneycontrol-2026-03"],
    },
    {
      id: "tribunal-encashment-2026",
      date: "2026-04-04",
      dateLabel: "4 April 2026",
      kind: "court",
      title: "Arbitral tribunal refuses L&T injunction; K-RIDE encashes ₹57 crore bank guarantees",
      body: "An arbitral tribunal of retired Supreme Court and High Court judges rejected L&T's plea to block encashment, upholding K-RIDE's position that L&T had defaulted on both corridor contracts and terminated them unlawfully. K-RIDE encashed performance bank guarantees worth ₹57 crore (Corridors 2 and 4, issued through YES Bank) on 4 April 2026. Arbitration on the parties' claims continues.",
      evidence: "reported",
      sourceIds: ["ie-2026-04"],
    },
    {
      id: "dec-2028-timeline-2026",
      date: "2026-06-29",
      dateLabel: "29 June 2026",
      kind: "deadline",
      title: "K-RIDE targets first services by December 2028, Corridor-2 first to open",
      body: "K-RIDE MD Lakshman Singh said first train services are expected by December 2028, with Corridor-2 leading the rollout. Two of the three Corridor-2 construction packages had been awarded and fresh bids invited for the remaining one; station construction had started on Corridors 2 and 4.",
      evidence: "reported",
      sourceIds: ["newsable-2026-06"],
    },
    {
      id: "lok-sabha-answer-2026",
      date: "2026-07-22",
      dateLabel: "22 July 2026",
      kind: "land",
      title: "Lok Sabha told Corridor 2 land acquisition is complete",
      body: "Answering Lok Sabha Unstarred Question No. 583, the Railways Minister said the project (148.17 km, ₹15,767 crore; 20% each from the Centre and Karnataka, 60% debt) had been affected by non-acquisition of private land, slow transfer of state government land and the absence of a full-time K-RIDE managing director, since appointed. For Corridor 2, the answer said the entire land acquisition is complete, contracts for station buildings have been awarded, and the tender for other works has been awarded with work in progress. The question itself cited an original October 2026 completion target.",
      evidence: "verified",
      sourceIds: ["sansad-2026-07"],
    },
    {
      id: "land-status-2026",
      date: "2026-08-06",
      dateLabel: "6 August 2026",
      kind: "land",
      title: "The Hindu reports a separate Lok Sabha reply on land",
      body: "Citing a Lok Sabha reply to a question by Chikkaballapur MP K. Sudhakar, The Hindu reported that Corridor 2 was the only corridor to have completed land acquisition and that the project had spent ₹2,659 crore. Its figures for the other corridors, and its account of the remaining Corridor 2 civil tenders, differ from the 22 July answer to Question No. 583.",
      evidence: "conflicting",
      sourceIds: ["thehindu-2026-08"],
    },
  ],
  signals: [
    {
      id: "agency",
      label: "Responsible agency",
      value: "K-RIDE",
      explanation: "A company controlled by the Government of Karnataka (51% equity) executes the project, per the Railways Minister's Lok Sabha answer. Lakshman Singh became K-RIDE's full-time managing director in December 2025; in July 2026 the government told the Lok Sabha that the earlier absence of one had affected progress.",
      evidence: "verified",
      asOf: "2026-07-22",
      sourceIds: ["sansad-2026-07", "newsable-2026-06"],
    },
    {
      id: "contractor",
      label: "Contractor",
      value: "L&T (terminated July 2025); balance re-tendered",
      explanation: "L&T held the Corridor 2 civil works contract from 26 August 2022 until it terminated the agreement in July 2025, citing land delays; K-RIDE calls the termination unilateral and illegal. The two accounts conflict and are before an arbitral tribunal. The contractors for the re-tendered packages were not found in primary records reviewed.",
      evidence: "conflicting",
      asOf: "2026-06-29",
      sourceIds: [
        "hindubusinessline-2025-08",
        "toi-2025-08",
        "hindu-2025-11",
        "newsable-2026-06",
        "moneycontrol-2026-03",
      ],
    },
    {
      id: "accepted-cost",
      label: "Accepted cost",
      value: "₹15,767 Cr sanctioned",
      explanation: "The sanctioned cost is verified in the Railways Minister's Lok Sabha answer. The 48% revision was reported by Moneycontrol citing the K-RIDE MD; a formal revised sanction document was not found in the public sources reviewed. No corridor-wise cost break-up is public.",
      evidence: "verified",
      asOf: "2026-07-22",
      sourceIds: ["sansad-2026-07", "moneycontrol-2026-03"],
    },
    {
      id: "litigation",
      label: "Litigation",
      value: "Arbitration ongoing",
      explanation: "L&T moved court after terminating the contracts; a Bengaluru commercial court dismissed its plea (9 Jan 2026) and an arbitral tribunal of retired SC/HC judges upheld K-RIDE's right to encash ₹57 crore in performance guarantees. The underlying claims (including L&T's ₹505 crore demand) remain in arbitration. Court orders were not found on Indian Kanoon or the High Court site; cited via news reports.",
      evidence: "reported",
      asOf: "2026-04-06",
      sourceIds: ["toi-2026-01", "ie-2026-04"],
    },
    {
      id: "land",
      label: "Land acquisition",
      value: "Complete for Corridor 2",
      explanation: "The Railways Minister told the Lok Sabha that Corridor 2's entire land acquisition has been completed. K-RIDE's managing director said the remaining land needs relate mainly to flyovers and rail overbridges.",
      evidence: "verified",
      asOf: "2026-07-22",
      sourceIds: ["sansad-2026-07", "newsable-2026-06"],
    },
    {
      id: "completion-target",
      label: "Latest completion target",
      value: "Dec 2028 (first services)",
      explanation: "Announced by K-RIDE MD Lakshman Singh in June 2026. The overall project deadline was separately reported extended to March 2030.",
      evidence: "reported",
      asOf: "2026-06-29",
      sourceIds: ["newsable-2026-06", "moneycontrol-2026-03"],
    },
  ],
  sources: [
    {
      id: "sansad-2026-07",
      title: "Lok Sabha Unstarred Question No. 583: Bengaluru Suburban Rail Project (answered 22.07.2026)",
      publisher: "Ministry of Railways, Government of India (sansad.in)",
      url: "https://sansad.in/getFile/lsapps/loksabhaquestions/annex/188/AU583_1DCngB.pdf",
      publishedOn: "2026-07-22",
      kind: "official",
    },
    {
      id: "toi-2020-10",
      title: "Mooted 37 yrs ago, 148km Bengaluru suburban rail project wins nod",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/mooted-37-yrs-ago-148km-bengaluru-suburban-rail-project-wins-nod/articleshow/78544898.cms",
      publishedOn: "2020-10-08",
      kind: "news",
    },
    {
      id: "toi-2025-08",
      title: "Bengaluru suburban rail project hits dead end as L&T walks out",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/bengaluru-suburban-rail-project-hits-dead-end-as-lt-walks-out/articleshow/123081313.cms",
      publishedOn: "2025-08-04",
      kind: "news",
    },
    {
      id: "hindubusinessline-2025-08",
      title: "L&T terminated Corridor-2, Corridor-4 contracts of Bengaluru suburban rail project illegally: K-RIDE",
      publisher: "The Hindu BusinessLine (PTI)",
      url: "https://www.thehindubusinessline.com/news/lt-terminated-corridor-2-corridor-4-contracts-of-bengaluru-suburban-rail-project-illegally-k-ride/article69889285.ece",
      publishedOn: "2025-08-03",
      kind: "news",
    },
    {
      id: "ie-2025-10",
      title: "K-RIDE to invite fresh tenders for Bengaluru suburban railway project's Corridor 2 after L&T walks out",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/k-ride-to-invite-fresh-tenders-for-bengaluru-suburban-railway-projects-corridor-2-after-lt-walks-out-10291523/",
      publishedOn: "2025-10-06",
      kind: "news",
    },
    {
      id: "hindu-2025-11",
      title: "K-RIDE invites fresh tenders for Mallige Line civil works after L&T contract termination",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/national/karnataka/k-ride-invites-fresh-tenders-for-mallige-line-civil-works-after-lt-contract-termination/article70240133.ece",
      publishedOn: "2025-11-04",
      kind: "news",
    },
    {
      id: "toi-2026-01",
      title: "L&T plea to restrain K-RIDE from invoking bank guarantees for Bengaluru Suburban Railway Project corridor 4 dismissed",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/lt-plea-to-restrain-k-ride-from-invoking-bank-guarantees-for-bengaluru-suburban-railway-project-corridor-4-dismissed/articleshow/126442262.cms",
      publishedOn: "2026-01-09",
      kind: "news",
    },
    {
      id: "moneycontrol-2026-03",
      title: "Bengaluru suburban rail project cost escalates from Rs 15,767 crore to Rs 23,342 crore due to delays, rolling stock procurement",
      publisher: "Moneycontrol",
      url: "https://www.moneycontrol.com/news/india/bengaluru-suburban-rail-project-cost-escalates-from-rs-15-767-crore-to-rs-23-342-crore-due-to-delays-rolling-stock-procurement-13859639.html",
      publishedOn: "2026-03-13",
      kind: "news",
    },
    {
      id: "ie-2026-04",
      title: "Bengaluru Suburban Rail Project: K-RIDE encashes Rs 57 crore bank guarantees after L&T dispute",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/k-ride-encashes-rs-57-crore-bank-guarantees-after-lt-dispute-10621383/",
      publishedOn: "2026-04-06",
      kind: "news",
    },
    {
      id: "newsable-2026-06",
      title: "Bengaluru Suburban Rail Project Update: K-RIDE Shares Fresh Timeline, Corridor 2 Set to Lead Rollout",
      publisher: "Asianet Newsable",
      url: "https://newsable.asianetnews.com/gallery/karnataka-news/bengaluru-suburban-rail-project-to-begin-by-december-2028-k-ride-says-project-will-transform-future-growth-in-bengaluru-5ish9bz",
      publishedOn: "2026-06-29",
      kind: "news",
    },
    {
      id: "thehindu-2026-08",
      title: "Only one of four Bengaluru suburban rail corridors clears land hurdle",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/only-one-of-four-bengaluru-suburban-rail-corridors-clears-land-hurdle/article71305542.ece",
      publishedOn: "2026-08-06",
      kind: "news",
    },
  ],
  suggestedQuestions: [
    "What was the Mallige Line contract L&T terminated worth, and what was paid?",
    "Who holds the re-tendered Mallige Line packages, and at what price?",
    "Has suburban rail's ₹23,342 crore revised cost been formally sanctioned?",
  ],
}
