import type { CivicProject } from "../civic-projects.ts"

export const cauveryWaterSupplySchemeStageV: CivicProject = {
  slug: "cauvery-water-supply-scheme-stage-v",
  cityId: "bengaluru",
  title: "Cauvery Water Supply Scheme Stage V",
  shortTitle: "Cauvery Stage V",
  routeName: "T.K. Halli to Bengaluru's 110 added villages",
  projectType: "Water supply and sewerage scheme",
  road: "T.K. Halli–Vajarahalli transmission main",
  status: "In progress",
  statusNote: "The water-supply system was inaugurated on 16 October 2024 after several missed commissioning dates. Connection and sewerage work was still reported incomplete in 2025 and 2026.",
  ownerAgency: "Bangalore Water Supply and Sewerage Board (BWSSB)",
  ownerAgencyShort: "BWSSB",
  nextTarget: "Not public",
  wardSignalNote: "BWSSB · ₹4,336 Cr JICA loan · no current completion target",
  affectedWards: [],
  wardBasis: "Not attached to wards. The sources reviewed have no ward-level service map for the 110 villages.",
  aliases: [
    "Cauvery Stage 5",
    "Cauvery water",
    "T.K. Halli",
    "Thorekadanahalli",
    "JICA",
    "SUEZ",
    "Toshiba",
    "Chokkanahalli",
    "sewage treatment plant",
    "sewerage",
  ],
  summary: "Cauvery Stage V adds a 775 MLD treatment and transmission system from T.K. Halli and was planned to extend water and sewerage service to 110 villages added to Bengaluru. The water-supply system opened in October 2024 after successive deadline changes, but public updates through 2026 still described incomplete connections, sewerage works and legal obstacles at specific facilities. The main evidence gap is a current package-by-package completion, payment and deadline register covering the whole scheme.",
  latestAsOf: "2026-09-16",
  alert: "The public record has no single, current completion target for the remaining sewerage and connection work.",
  metrics: [
    {
      label: "Treatment capacity",
      value: "775 MLD",
      note: "The Stage V treatment plant at T.K. Halli, per the plant contractor's award announcement.",
      evidence: "reported",
    },
    {
      label: "JICA loan",
      value: "₹4,336 Cr",
      note: "JPY 81,060 million (about ₹4,336 crore), per JICA. Its 2017 appraisal estimated the whole project at JPY 153,837 million; news reports give a ₹5,500–5,550 crore project cost.",
      evidence: "verified",
    },
    {
      label: "Connections",
      value: "~2 of 3.5 lakh",
      note: "BWSSB data reported by The Hindu in October 2025. JICA's launch note set a 4 lakh target, so the target itself is not reconciled.",
      evidence: "conflicting",
    },
    {
      label: "Villages served",
      value: "110",
      note: "Villages added to Bengaluru that the scheme is meant to serve, per JICA.",
      evidence: "verified",
    },
  ],
  records: [
    {
      id: "jica-loan-agreement-2018",
      date: "2018-01-24",
      dateLabel: "24 January 2018",
      kind: "start",
      title: "First JICA loan agreement",
      body: "JICA's ex-ante evaluation records the Phase 3 (I) loan agreement and a project schedule beginning in January 2018.",
      evidence: "verified",
      sourceIds: ["jica-exante-2017"],
    },
    {
      id: "tk-halli-award-2020",
      date: "2020-11-05",
      dateLabel: "5 November 2020",
      kind: "accountability",
      title: "T.K. Halli treatment-plant order announced",
      body: "Toshiba announced that BWSSB awarded SUEZ India and Toshiba Water Solutions the design, construction and commissioning work for the 775 MLD T.K. Halli plant, with seven years of operations and maintenance and a stated 30-month construction period.",
      evidence: "reported",
      sourceIds: ["toshiba-award-2020"],
    },
    {
      id: "second-jica-loan-2022",
      date: "2022-03-31",
      dateLabel: "31 March 2022",
      kind: "cost",
      title: "Second JICA loan signed",
      body: "JICA announced a JPY 37,068 million loan, approximately ₹2,391 crore, for Phase 3 (II) water-supply and sewerage facilities.",
      evidence: "verified",
      sourceIds: ["jica-loan-2022"],
    },
    {
      id: "july-2023-deadline",
      date: "2023-07-31",
      dateLabel: "July 2023",
      kind: "deadline",
      title: "July 2023 completion date missed",
      body: "Later reporting said the state had extended the project's July 2023 deadline by six months.",
      evidence: "reported",
      sourceIds: ["tnie-deadline-2023"],
    },
    {
      id: "december-2023-extension",
      date: "2023-12-31",
      dateLabel: "December 2023",
      kind: "deadline",
      title: "Six-month extension also passed",
      body: "The December 2023 report said the state had granted a six-month extension from July to December 2023, while BWSSB then expected infrastructure by March 2024 and commissioning by May 2024.",
      evidence: "reported",
      sourceIds: ["tnie-deadline-2023"],
    },
    {
      id: "may-2024-target",
      date: "2024-05-31",
      dateLabel: "May 2024",
      kind: "deadline",
      title: "May commissioning target missed",
      body: "BWSSB's chairman had publicly targeted commissioning by May 2024; June reporting said the launch moved first to June and then to the first week of July.",
      evidence: "reported",
      sourceIds: ["tnie-deadline-2023", "tnie-delay-2024"],
    },
    {
      id: "july-2024-target",
      date: "2024-07-07",
      dateLabel: "First week of July 2024",
      kind: "deadline",
      title: "July commissioning target announced",
      body: "BWSSB officials said physical work, gap filling and testing would finish by June-end and public benefit would begin in the first week of July.",
      evidence: "reported",
      sourceIds: ["tnie-delay-2024"],
    },
    {
      id: "october-2024-inauguration",
      date: "2024-10-16",
      dateLabel: "16 October 2024",
      kind: "deadline",
      title: "Stage V water-supply system inaugurated",
      body: "JICA recorded the unveiling at T.K. Halli on 16 October 2024. The same note said JICA anticipates the full opening of the project and the inauguration of wastewater treatment facilities.",
      evidence: "verified",
      sourceIds: ["jica-inauguration-2024"],
    },
    {
      id: "connections-update-2025",
      date: "2025-10-08",
      dateLabel: "8 October 2025",
      kind: "accountability",
      title: "Connection rollout remained incomplete",
      body: "The Hindu reported BWSSB data showing about 2 lakh connections against a 3.5 lakh target, including 87,000 added in the year after inauguration; it also reported that 24,000 applications citywide were held up by occupancy-certificate rules, without a Stage V breakup.",
      evidence: "reported",
      sourceIds: ["hindu-connections-2025"],
    },
    {
      id: "legal-and-sewerage-update-2026",
      date: "2026-01-14",
      dateLabel: "14 January 2026",
      kind: "court",
      title: "Legal and sewerage obstacles reported",
      body: "The Hans India, attributing information to BWSSB officials, reported land disputes affecting a Chokkanahalli reservoir and a Supreme Court case stalling a 25 MLD Varthur sewage-treatment plant. The report did not identify the case number or order, so those litigation details remain unverified in the primary court record reviewed.",
      evidence: "reported",
      sourceIds: ["hans-legal-2026"],
    },
  ],
  signals: [
    {
      id: "responsible-agency",
      label: "Responsible agency",
      value: "BWSSB",
      explanation: "JICA names BWSSB as executing agency.",
      evidence: "verified",
      asOf: "2017-12-01",
      sourceIds: ["jica-exante-2017"],
    },
    {
      id: "contractor",
      label: "Contractor",
      value: "SUEZ India and Toshiba (T.K. Halli plant)",
      explanation: "Toshiba's order announcement names the joint awardees and package scope. A consolidated primary contractor register for every Stage V package was not found in the public sources reviewed.",
      evidence: "reported",
      asOf: "2020-11-05",
      sourceIds: ["toshiba-award-2020"],
    },
    {
      id: "accepted-cost",
      label: "Accepted cost",
      value: "No current official rupee total",
      explanation: "JICA's 2017 appraisal estimated the project at JPY 153,837 million, including a JPY 81,060 million loan (about ₹4,336 crore). News reports cite a ₹5,500–5,550 crore project cost. No current official rupee total was found in the public sources reviewed.",
      evidence: "reported",
      asOf: "2026-01-14",
      sourceIds: ["jica-exante-2017", "jica-inauguration-2024", "tnie-deadline-2023", "hans-legal-2026"],
    },
    {
      id: "litigation",
      label: "Litigation",
      value: "Two disputes reported; case details not public",
      explanation: "A 2026 report attributes these obstacles to BWSSB officials, but the case title, number and court order were not found in the public sources reviewed.",
      evidence: "reported",
      asOf: "2026-01-14",
      sourceIds: ["hans-legal-2026"],
    },
  ],
  sources: [
    {
      id: "jica-exante-2017",
      title: "Ex-Ante Evaluation: Bengaluru Water Supply and Sewerage Project (Phase 3) (I)",
      publisher: "Japan International Cooperation Agency",
      url: "https://www2.jica.go.jp/en/evaluation/pdf/2017_ID-P266_1_f.pdf",
      publishedOn: "2017-12-01",
      kind: "official",
    },
    {
      id: "toshiba-award-2020",
      title: "Bangalore Water Supply and Sewerage Board awards an Order to SUEZ India & Toshiba Water Solutions for construction of Water Treatment Plant",
      publisher: "Toshiba Infrastructure Systems & Solutions Corporation",
      url: "https://www.global.toshiba/ww/news/infrastructure/2020/11/news-20201105-01.html",
      publishedOn: "2020-11-05",
      kind: "company",
    },
    {
      id: "jica-loan-2022",
      title: "JICA extends ODA loan of INR 2391 crores for Bengaluru Water Supply and Sewerage Project (Phase 3)",
      publisher: "Japan International Cooperation Agency",
      url: "https://www.jica.go.jp/english/overseas/india/information/press/2021/press220331_04.html",
      publishedOn: "2022-03-31",
      kind: "official",
    },
    {
      id: "tnie-deadline-2023",
      title: "110 villages to get Cauvery water only by May-end",
      publisher: "The New Indian Express",
      url: "https://www.newindianexpress.com/cities/bengaluru/2023/Dec/23/110-villages-to-get-cauvery-water-only-by-may-end-2644167.html",
      publishedOn: "2023-12-23",
      kind: "news",
    },
    {
      id: "tnie-delay-2024",
      title: "Expect delay with Cauvery Stage V project",
      publisher: "The New Indian Express",
      url: "https://www.newindianexpress.com/cities/bengaluru/2024/Jun/07/expect-delay-with-cauvery-stage-v-project",
      publishedOn: "2024-06-07",
      kind: "news",
    },
    {
      id: "jica-inauguration-2024",
      title: "Unveiling of the JICA-funded 5th stage of Cauvery Water Supply Scheme",
      publisher: "Japan International Cooperation Agency",
      url: "https://www.jica.go.jp/english/overseas/india/information/press/2024/1553733_53431.html",
      publishedOn: "2024-10-16",
      kind: "official",
    },
    {
      id: "hindu-connections-2025",
      title: "In a year since Cauvery Stage V was commissioned, 87,000 got new connections",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/national/karnataka/in-a-year-since-cauvery-stage-v-was-commissioned-87000-got-new-connections/article70139770.ece",
      publishedOn: "2025-10-08",
      kind: "news",
    },
    {
      id: "hans-legal-2026",
      title: "Legal hurdles delay Cauvery Stage V Project",
      publisher: "The Hans India",
      url: "https://www.thehansindia.com/karnataka/legal-hurdles-delay-cauvery-stage-v-project-1039329",
      publishedOn: "2026-01-14",
      kind: "news",
    },
  ],
  suggestedQuestions: [
    "When will the remaining Stage V sewerage and connection work be complete?",
    "Has BWSSB published one reconciled project cost?",
    "Which court cases are holding up Cauvery Stage V facilities?",
  ],
}
