import type { CivicProject } from "../civic-projects.ts"

export const ejipuraKendriyaSadanFlyover: CivicProject = {
  slug: "ejipura-kendriya-sadan-flyover",
  cityId: "bengaluru",
  title: "Ejipura–Kendriya Sadan flyover",
  shortTitle: "Ejipura flyover",
  routeName: "Ejipura Junction to Kendriya Sadan",
  projectType: "Elevated flyover",
  road: "Intermediate Ring Road, Koramangala",
  status: "Delayed",
  statusNote: "Work began in 2017 with a November 2019 deadline. The latest reported target is opening to traffic in November 2026, after an October 2026 target reported in May.",
  ownerAgency: "Greater Bengaluru Authority (GBA), formerly BBMP",
  ownerAgencyShort: "GBA",
  nextTarget: "Nov 2026",
  wardSignalNote: "GBA · ₹307.96 Cr revised cost reported · Nov 2026 target",
  affectedWards: [
    { corporationId: 1, corporation: "Central", wardNo: 24, name: "Agaram" },
    { corporationId: 4, corporation: "South", wardNo: 24, name: "A Adugodi" },
    { corporationId: 4, corporation: "South", wardNo: 27, name: "Sri Lakshmi Devi Ward" },
    { corporationId: 4, corporation: "South", wardNo: 28, name: "Kormangala East" },
    { corporationId: 4, corporation: "South", wardNo: 29, name: "Kormangala West" },
  ],
  wardBasis: "Wards within 40 m of the flyover as mapped in OpenStreetMap (checked 17 September 2026). Kaun derived this list; the agency does not publish one.",
  aliases: [
    "Ejipura flyover",
    "Koramangala flyover",
    "Kendriya Sadana",
    "Sony World Junction",
    "Intermediate Ring Road",
  ],
  summary: "The roughly 2.5 km flyover from Ejipura Junction to Kendriya Sadan began under BBMP in 2017 and missed its November 2019 deadline, then went through contract cancellation and repeat tenders. Reporting says the Karnataka cabinet revised the project cost to ₹307.96 crore in September 2023, while later public updates moved the completion target repeatedly. The reviewed public sources did not include the operative work order, current accepted contract value and payment schedule, or an official progress report as of the review date.",
  latestAsOf: "2026-09-16",
  alert: "The current work order, milestone schedule, payments and a dated official progress report were not found in the public sources reviewed.",
  metrics: [
    {
      label: "Length",
      value: "2.5 km",
      note: "Reported consistently in court coverage and project reporting.",
      evidence: "reported",
    },
    {
      label: "Original cost",
      value: "₹203–204 Cr",
      note: "Reports give both figures; the sources reviewed do not reconcile them.",
      evidence: "conflicting",
    },
    {
      label: "Revised cost",
      value: "₹307.96 Cr",
      note: "The Hindu reported a cabinet revision in September 2023; the cabinet record itself was not found.",
      evidence: "reported",
    },
    {
      label: "Original deadline",
      value: "Nov 2019",
      note: "The May 2017 work order allowed 30 months, per court reporting.",
      evidence: "reported",
    },
  ],
  records: [
    {
      id: "original-work-order",
      date: "2017-05-04",
      dateLabel: "4 May 2017",
      kind: "start",
      title: "Original work order issued",
      body: "Court reporting states that BBMP issued the construction work order on 4 May 2017, at a reported cost of ₹203 crore, with a 30-month delivery period.",
      evidence: "reported",
      sourceIds: ["hindu-hc-timeline-2021", "livelaw-fir-direction-2022"],
    },
    {
      id: "original-deadline",
      date: "2019-11-04",
      dateLabel: "November 2019",
      kind: "deadline",
      title: "Original completion period ran out",
      body: "The 30-month period from the May 2017 work order ran out in November 2019 without the flyover being completed.",
      evidence: "reported",
      sourceIds: ["hindu-hc-timeline-2021", "ie-hc-second-chance-2022"],
    },
    {
      id: "extended-deadline-2020",
      date: "2020-12-31",
      dateLabel: "December 2020",
      kind: "deadline",
      title: "Extended deadline also missed",
      body: "The PIL petitioner told the High Court that BBMP had extended the deadline to December 2020 after imposing a penalty for delay, and that the work was still incomplete.",
      evidence: "reported",
      sourceIds: ["hindu-hc-timeline-2021"],
    },
    {
      id: "high-court-seeks-timeline",
      date: "2021-07-29",
      dateLabel: "29 July 2021",
      kind: "court",
      title: "High Court seeks a completion timeline",
      body: "In PIL proceedings, the Karnataka High Court directed BBMP to state its timeline for completing the flyover. The petitioner said only about half the work had been completed.",
      evidence: "reported",
      sourceIds: ["hindu-hc-timeline-2021"],
    },
    {
      id: "high-court-fir-direction",
      date: "2022-02-17",
      dateLabel: "17 February 2022",
      kind: "court",
      title: "High Court directs BBMP to lodge an FIR and act on the contract",
      body: "The High Court was reported to have directed the BBMP commissioner to lodge an FIR concerning alleged misappropriation of public funds and to take steps including contract cancellation. This entry records the court direction as reported and does not state the outcome of any investigation.",
      evidence: "reported",
      sourceIds: ["livelaw-fir-direction-2022"],
    },
    {
      id: "state-cancels-original-contract",
      date: "2022-03-08",
      dateLabel: "8 March 2022",
      kind: "accountability",
      title: "State cancels the original contract",
      body: "The Urban Development Department was reported to have cancelled the contract and ordered forfeiture of a ₹10.16 crore security deposit. The report said progress stood at 42.83% and directed BBMP to retender the remainder within the ₹204 crore project cost.",
      evidence: "reported",
      sourceIds: ["hindu-contract-cancelled-2022"],
    },
    {
      id: "december-2022-undertaking-target",
      date: "2022-03-29",
      dateLabel: "29 March 2022",
      kind: "deadline",
      title: "Court permits an undertaking for completion by December 2022",
      body: "The High Court gave the original contractor an opportunity to file an undertaking to complete the flyover by 31 December 2022. In January 2023, BBMP invited bids to complete the project.",
      evidence: "reported",
      sourceIds: ["ie-hc-second-chance-2022", "ie-third-tender-scrapped-2023"],
    },
    {
      id: "third-retender-cancelled",
      date: "2023-02-17",
      dateLabel: "17 February 2023",
      kind: "cost",
      title: "Third tender attempt scrapped over price",
      body: "BBMP scrapped its third tender to complete the flyover. The lone bidder quoted ₹205 crore against an estimate of ₹144 crore, and officials said the estimate would be reviewed.",
      evidence: "reported",
      sourceIds: ["ie-third-tender-scrapped-2023"],
    },
    {
      id: "cabinet-cost-revision",
      date: "2023-09-01",
      dateLabel: "September 2023",
      kind: "cost",
      title: "Cabinet reportedly revises total project cost",
      body: "The Hindu later reported that the Karnataka cabinet agreed to revise the total project cost to ₹307.96 crore in September 2023. The exact cabinet decision date and primary cabinet record were not found in the public sources reviewed.",
      evidence: "reported",
      sourceIds: ["hindu-project-history-2024"],
    },
    {
      id: "new-work-order-reported",
      date: "2023-11-01",
      dateLabel: "November 2023",
      kind: "start",
      title: "Completion contract announced with a 15-month target",
      body: "BBMP was reported to have announced a new completion contract in November 2023 with a 15-month deadline. The operative work order and exact commencement date were not found in the public sources reviewed.",
      evidence: "reported",
      sourceIds: ["hindu-project-history-2024"],
    },
    {
      id: "october-2026-target",
      date: "2026-05-21",
      dateLabel: "21 May 2026",
      kind: "deadline",
      title: "Completion target moves to October 2026",
      body: "GBA's chief commissioner was reported to have directed additional deployment to meet an end-October 2026 target. The update reported 731 of 762 segments cast and 52 of 66 spans completed.",
      evidence: "reported",
      sourceIds: ["hindu-october-target-2026"],
    },
    {
      id: "november-2026-target",
      date: "2026-08-26",
      dateLabel: "26 August 2026",
      kind: "deadline",
      title: "Latest reported target moves to November 2026",
      body: "Transport Minister Ramalinga Reddy was reported as saying most work was complete and the flyover would open to traffic in November 2026. No later official completion report was found by the 16 September review date.",
      evidence: "reported",
      sourceIds: ["publictv-november-target-2026"],
    },
  ],
  signals: [
    {
      id: "responsible-agency",
      label: "Responsible agency",
      value: "GBA (formerly BBMP)",
      explanation: "BBMP procured and managed the project; 2026 updates describe directions by the GBA chief commissioner.",
      evidence: "reported",
      asOf: "2026-09-16",
      sourceIds: ["hindu-hc-timeline-2021", "hindu-october-target-2026"],
    },
    {
      id: "contractor",
      label: "Contractor",
      value: "Not in primary records reviewed",
      explanation: "News and court reporting names the original and replacement firms, but the evidence rules require a primary record before naming a contractor. The original and current work orders were not found in the public sources reviewed.",
      evidence: "unknown",
      asOf: "2026-09-16",
      sourceIds: [],
    },
    {
      id: "accepted-cost",
      label: "Accepted cost",
      value: "₹307.96 Cr reported; current contract value unknown",
      explanation: "A September 2023 cabinet revision to ₹307.96 crore was reported, but the primary cabinet record and current work order were not found. Other reports cite ₹176 crore for pending work, which is a different cost basis and is not treated as the total project cost.",
      evidence: "reported",
      asOf: "2023-09-01",
      sourceIds: ["hindu-project-history-2024", "toi-resumption-2023"],
    },
    {
      id: "litigation",
      label: "Litigation",
      value: "PIL W.P. 13605/2021",
      explanation: "Court reporting identifies Adinarayan Shetty v. State of Karnataka as a PIL over delay. Reported directions included submission of a time-bound plan, action on the contract, and an opportunity for a completion undertaking.",
      evidence: "reported",
      asOf: "2022-03-29",
      sourceIds: ["livelaw-fir-direction-2022", "ie-hc-second-chance-2022"],
    },
    {
      id: "official-progress-record",
      label: "Official progress record",
      value: "Not found publicly",
      explanation: "The reviewed sources did not provide a current agency progress report with a dated physical and financial progress statement as of 16 September 2026.",
      evidence: "unknown",
      asOf: "2026-09-16",
      sourceIds: [],
    },
  ],
  sources: [
    {
      id: "hindu-hc-timeline-2021",
      title: "Ejipura-Koramangala flyover: State timeline for completing project",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/ejipura-koramangala-flyover-state-timeline-for-completing-project/article35617463.ece",
      publishedOn: "2021-07-29",
      kind: "news",
    },
    {
      id: "livelaw-fir-direction-2022",
      title: "Ejipura-Kendriya Sadana Flyover: Karnataka High Court Directs BBMP To Lodge FIR Against Contractor",
      publisher: "LiveLaw",
      url: "https://www.livelaw.in/news-updates/karnataka-high-court-directs-bbmp-to-lodge-fir-ejipura-kendriya-sadana-flyover-192175",
      publishedOn: "2022-02-17",
      kind: "news",
    },
    {
      id: "hindu-contract-cancelled-2022",
      title: "Government cancels Ejipura flyover tender",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/government-cancels-ejipura-flyover-tender/article65204567.ece",
      publishedOn: "2022-03-08",
      kind: "news",
    },
    {
      id: "ie-hc-second-chance-2022",
      title: "Karnataka HC gives contractor another chance to complete Ejipura flyover by Dec 31",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/bengaluru-karnataka-hc-gives-contractor-complete-ejipura-flyover-dec-31-7845008/",
      publishedOn: "2022-03-30",
      kind: "news",
    },
    {
      id: "ie-third-tender-scrapped-2023",
      title: "Ejipura-Kendriya Sadan flyover tender scrapped for third time, this time over cost estimation",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/bengaluru-bbmp-scraps-ejipura-kendriya-sadan-flyover-tender-for-third-time-8462268/",
      publishedOn: "2023-02-23",
      kind: "news",
    },
    {
      id: "toi-resumption-2023",
      title: "Palike all set to resume Ejipura flyover project",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/palike-all-set-to-resume-ejipura-flyover-project/articleshow/104683910.cms",
      publishedOn: "2023-10-25",
      kind: "news",
    },
    {
      id: "hindu-project-history-2024",
      title: "Contractor issues and environmental hurdles make Ejipura flyover project a jinxed one",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/the-jinxed-ejipura-flyover-delays-amid-contractor-issues-and-environmental-hurdles/article68251433.ece",
      publishedOn: "2024-06-12",
      kind: "news",
    },
    {
      id: "hindu-october-target-2026",
      title: "GBA chief orders manpower boost for timely Ejipura Flyover construction",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/gba-chief-orders-manpower-boost-for-timely-ejipura-flyover-construction/article71006863.ece",
      publishedOn: "2026-05-21",
      kind: "news",
    },
    {
      id: "publictv-november-target-2026",
      title: "Ejipura flyover to finally open to traffic in November",
      publisher: "Public TV English",
      url: "https://english.publictv.in/ejipura-flyover-to-finally-open-to-traffic-in-november/",
      publishedOn: "2026-08-26",
      kind: "news",
    },
  ],
  suggestedQuestions: [
    "Can GBA publish the current work order, milestone schedule and monthly progress report?",
    "How much has the project cost in total, and how much has been paid to each contract so far?",
    "What work remains before the Ejipura flyover opens?",
  ],
}
