import type { CivicProject } from "../civic-projects.ts"

export const nammaMetroPhase2aOrr: CivicProject = {
  slug: "namma-metro-phase-2a-orr",
  cityId: "bengaluru",
  title: "Namma Metro Phase 2A: Central Silk Board to KR Puram",
  shortTitle: "ORR Metro (Phase 2A)",
  routeName: "Central Silk Board to KR Puram",
  projectType: "Elevated metro line",
  road: "Outer Ring Road",
  status: "Delayed",
  statusNote: "Civil work began in mid-2021 on 30-month contracts. The opening target has moved from 2021 to about mid-2027, and trial runs from October 2026 will skip two unfinished stations.",
  ownerAgency: "Bangalore Metro Rail Corporation Limited (BMRCL)",
  ownerAgencyShort: "BMRCL",
  nextTarget: "Mid-2027",
  wardSignalNote: "BMRCL · opening moved to mid-2027 · 2 stations unfinished",
  affectedWards: [
    { corporationId: 1, corporation: "Central", wardNo: 12, name: "Kasturi Nagar" },
    { corporationId: 1, corporation: "Central", wardNo: 13, name: "Krishnaiahnapalya" },
    { corporationId: 1, corporation: "Central", wardNo: 24, name: "Agaram" },
    { corporationId: 3, corporation: "East", wardNo: 18, name: "Dooravaninagar" },
    { corporationId: 3, corporation: "East", wardNo: 19, name: "K.S. Nissar Ahmed Ward" },
    { corporationId: 3, corporation: "East", wardNo: 20, name: "A Narayanapura" },
    { corporationId: 3, corporation: "East", wardNo: 22, name: "Mahadevapura" },
    { corporationId: 3, corporation: "East", wardNo: 36, name: "Bharath Aikya Ward" },
    { corporationId: 3, corporation: "East", wardNo: 41, name: "Munnenkolalu" },
    { corporationId: 3, corporation: "East", wardNo: 42, name: "Priyadarshini Ward" },
    { corporationId: 3, corporation: "East", wardNo: 43, name: "Dodda Nekkundi" },
    { corporationId: 3, corporation: "East", wardNo: 44, name: "Ashwath Nagar" },
    { corporationId: 3, corporation: "East", wardNo: 45, name: "Marathahalli" },
    { corporationId: 3, corporation: "East", wardNo: 47, name: "Bellanduru" },
    { corporationId: 3, corporation: "East", wardNo: 48, name: "Panathur" },
    { corporationId: 3, corporation: "East", wardNo: 49, name: "Shivanasamudra Ward" },
    { corporationId: 4, corporation: "South", wardNo: 18, name: "Viswamanava Kuvempu Ward" },
    { corporationId: 4, corporation: "South", wardNo: 20, name: "Madiwala" },
    { corporationId: 4, corporation: "South", wardNo: 30, name: "Jakkasandra" },
    { corporationId: 4, corporation: "South", wardNo: 70, name: "Iblur" },
    { corporationId: 4, corporation: "South", wardNo: 72, name: "HSR Layout" },
  ],
  wardBasis: "Wards within 40 m of the line as mapped in OpenStreetMap (checked 17 September 2026). Kaun derived this list; the agency does not publish one.",
  aliases: [
    "ORR metro",
    "Blue Line",
    "Phase 2A",
    "Silk Board",
    "KR Puram",
    "Afcons",
    "Shankaranarayana Constructions",
    "metro station",
  ],
  summary: "Phase 2A is a 19.75 km, 13-station elevated Blue Line section along the Outer Ring Road IT corridor, from Central Silk Board to KR Puram, approved by the Union Cabinet in April 2021 together with Phase 2B at ₹14,788.101 crore. Afcons Infrastructure and Shankaranarayana Constructions began civil work in mid-2021 on 30-month contracts; the opening has since moved from 2021 (2016 DPR) to about mid-2027, with October 2026 trial runs skipping the unfinished Marathahalli and Silk Board stations. Main evidence gap: no Phase-2A-specific cost, progress, or contractor delay figures are public — the sanctioned cost and the 72.75% progress both combine Phases 2A and 2B.",
  latestAsOf: "2026-09-16",
  alert: "No Phase 2A-only cost or progress figure is public. The ₹14,788 crore sanction and the 72.75% progress figure (June 2026) both combine Phases 2A and 2B.",
  metrics: [
    {
      label: "Length",
      value: "19.75 km",
      note: "13 elevated stations, per BMRCL's January 2023 presentation. The 2021 sanction covers 58.19 km across Phases 2A and 2B.",
      evidence: "verified",
    },
    {
      label: "Sanctioned cost (2A + 2B)",
      value: "₹14,788 Cr",
      note: "Union Cabinet approval, 20 April 2021. No Phase 2A-only figure is published; the 2016 DPR estimated ₹4,202 crore for this corridor.",
      evidence: "verified",
    },
    {
      label: "Civil contracts",
      value: "₹1,409 Cr",
      note: "Afcons ₹785.23 crore (Package 1) and Shankaranarayana Constructions ₹623.55 crore (Package 2), per BMRCL's January 2023 presentation.",
      evidence: "verified",
    },
    {
      label: "Progress (2A + 2B)",
      value: "72.75%",
      note: "As of June 2026, per the Union housing ministry's Lok Sabha reply reported by The Indian Express. No Phase 2A-only figure is published.",
      evidence: "reported",
    },
  ],
  records: [
    {
      id: "dpr-2016",
      date: "2016-10-01",
      dateLabel: "October 2016",
      kind: "start",
      title: "DPR: ORR metro estimated at ₹4,202 crore, operational by 2021",
      body: "BMRCL's in-house team prepared the detailed project report for the Central Silk Board-KR Puram corridor in October 2016, estimating ₹4,202 crore and operation by 2021. A tender floated in 2018 was cancelled after the cash-strapped IL&FS emerged lowest bidder in all packages.",
      evidence: "reported",
      sourceIds: ["toi-2019-12-20"],
    },
    {
      id: "tenders-2019",
      date: "2019-12-20",
      dateLabel: "20 December 2019",
      kind: "start",
      title: "BMRCL floats civil tenders in two packages",
      body: "BMRCL invited tenders for the roughly 19 km elevated corridor with 13 stations: Package 1 (9.85 km, 6 stations plus a 2.8 km flyover at Silk Board, estimate ₹731.2 crore) and Package 2 (9.74 km, 7 stations plus a link line to Byappanahalli depot, estimate ₹594.2 crore). A senior official said a December 2023 deadline was still possible; sources put the revised corridor estimate at about ₹5,300 crore.",
      evidence: "reported",
      sourceIds: ["toi-2019-12-20"],
    },
    {
      id: "bid-opening-2020",
      date: "2020-10-13",
      dateLabel: "13 October 2020",
      kind: "cost",
      title: "Financial bids opened: Afcons lowest for Package 1, Shankaranarayana for Package 2",
      body: "Afcons Infrastructure quoted ₹785.25 crore against an estimate of ₹731.18 crore for Package 1 (Silk Board-Kadubeesanahalli), and Shankaranarayana Constructions quoted ₹623.55 crore against ₹594.25 crore for Package 2 (Kodibeesanahalli-KR Puram).",
      evidence: "reported",
      sourceIds: ["tmg-2020-10-13"],
    },
    {
      id: "cabinet-approval-2021",
      date: "2021-04-20",
      dateLabel: "20 April 2021",
      kind: "cost",
      title: "Union Cabinet approves Phases 2A and 2B: 58.19 km, ₹14,788.101 crore",
      body: "The Union Cabinet approved Phase 2A (Central Silk Board Junction to KR Puram) and Phase 2B (KR Puram to the airport via Hebbal), 58.19 km in all, at a completion cost of ₹14,788.101 crore. The Hindu reported that the project would be completed in five years if all went as planned, and that land acquisition for Phase 2A was already complete.",
      evidence: "verified",
      sourceIds: ["pib-2021-04-20", "hindu-2021-04-20"],
    },
    {
      id: "contract-award-2021",
      date: "2021-05-26",
      dateLabel: "26 May 2021",
      kind: "cost",
      title: "BMRCL awards two civil contracts worth about ₹1,409 crore",
      body: "Contract PHASE 2A/P1/60(a) to Afcons Infrastructure (₹785 crore, 30 months) and PHASE 2A/P2/60(b) to Shankaranarayana Constructions (₹623 crore, 30 months), covering the full 18.3-19.75 km corridor and its 13 stations.",
      evidence: "reported",
      sourceIds: ["mrn-2021-05-26"],
    },
    {
      id: "sanction-order-2021",
      date: "2021-06-07",
      dateLabel: "7 June 2021",
      kind: "deadline",
      title: "Central sanction order sets five-year completion",
      body: "The Ministry of Housing and Urban Affairs issued the sanction order for the 58 km Central Silk Board-KIA line at ₹14,788.101 crore, to be completed in five years; Centre and State to fund 20% each, 60% by loans.",
      evidence: "reported",
      sourceIds: ["hindu-2021-06-08"],
    },
    {
      id: "construction-start-2021",
      date: "2021-06-28",
      dateLabel: "June-July 2021",
      kind: "start",
      title: "Civil work begins; both contracts expected complete by 30 June 2024",
      body: "BMRCL's own presentation records Package 2 starting 28 June 2021 and Package 1 starting 5 July 2021, each with an expected completion date of 30 June 2024. It also records that tree clearance permission took about 8 months and the GAIL gas line shift took 12 months from project commencement.",
      evidence: "verified",
      sourceIds: ["bmrcl-ppt-2023-01"],
    },
    {
      id: "tree-order-2021",
      date: "2021-12-24",
      dateLabel: "24 December 2021",
      kind: "court",
      title: "High Court permits felling 577 trees, translocating 212 on Silk Board-Kadubeesanahalli stretch",
      body: "A division bench of the Karnataka High Court permitted BMRCL to remove 833 trees (577 felled, 212 translocated, 44 retained) between Central Silk Board and Kadubeesanahalli, acting on the court-appointed Technical Expert Committee's recommendation. BMRCL had applied in June 2021; a second application for 1,026 trees between Kadubeesanahalli and KR Puram was pending.",
      evidence: "reported",
      sourceIds: ["swarajya-2021-12-25"],
    },
    {
      id: "completion-target-2023",
      date: "2023-01-10",
      dateLabel: "10 January 2023",
      kind: "deadline",
      title: "BMRCL presentation still shows 30 June 2024 expected completion for both packages",
      body: "In a presentation to the Outer Ring Road Companies Association, BMRCL listed both civil packages with expected completion on 30 June 2024, contract values ₹785.23 crore (Afcons) and ₹623.55 crore (Shankaranarayana), and the 13-station list for the 19.75 km corridor.",
      evidence: "verified",
      sourceIds: ["bmrcl-ppt-2023-01"],
    },
    {
      id: "royal-heritage-wp-2023",
      date: "2023-07-14",
      dateLabel: "14 July 2023",
      kind: "court",
      title: "High Court disposes of acquisition writs over metro land near KR Puram",
      body: "In Royal Heritage Apartment Owners' Association vs BMRCL (WP 16862/2021 c/w WP 490/2023), the Karnataka High Court disposed by consent of challenges to KIADB acquisition notifications of 2021 for land at Benniganahalli village, KR Puram Hobli, abutting BMRCL property. The acquired area was cut from 261.28 to 119.68 sq m, the General Award of 21 Dec 2021 was quashed, and compensation of about ₹2.54 crore was agreed under Section 29(2) of the KIAD Act, with structure valuation sent to the Reference Court. The order does not state which metro phase the land was for.",
      evidence: "verified",
      sourceIds: ["ik-royal-heritage-2023"],
    },
    {
      id: "dec-2026-target-2025",
      date: "2025-10-02",
      dateLabel: "2 October 2025",
      kind: "deadline",
      title: "BMRCL tells ORRCA the line will open only by December 2026",
      body: "At a review meeting with the Outer Ring Road Companies Association, BMRCL's managing director said the Silk Board–KR Puram line would be ready for operations by December 2026, BLR Post reported.",
      evidence: "reported",
      sourceIds: ["blrpost-2025-10-02"],
    },
    {
      id: "progress-72pct-2026",
      date: "2026-07-30",
      dateLabel: "30 July 2026",
      kind: "accountability",
      title: "MoHUA tells Lok Sabha Phases 2A+2B are 72.75% complete",
      body: "The Union Ministry of Housing and Urban Affairs told the Lok Sabha that Phases 2A and 2B (58.19 km) were 72.75% complete as of June 2026. BMRCL said the Silk Board-KR Puram stretch should open by late 2026. The reply does not break out Phase 2A alone.",
      evidence: "reported",
      sourceIds: ["ie-2026-08-05"],
    },
    {
      id: "walkway-contract-2026",
      date: "2026-08-14",
      dateLabel: "14 August 2026",
      kind: "cost",
      title: "Silk Board interchange walkway contract awarded for ₹55.48 crore",
      body: "BMRCL awarded the elevated travelator/walkway linking the Blue Line and Yellow Line stations at Silk Board to Milan Road Buildtech LLP for ₹55.48 crore against an estimate of ₹58.99 crore, with nine months for completion.",
      evidence: "reported",
      sourceIds: ["swarajya-2026-08-19"],
    },
    {
      id: "trials-oct-2026",
      date: "2026-08-18",
      dateLabel: "August 2026",
      kind: "scope",
      title: "Trial runs set for October 2026 but will skip two unfinished stations",
      body: "Trial runs are planned from October 2026 in two segments (KR Puram-Marathahalli and Marathahalli-HSR Layout), skipping Marathahalli and Silk Board stations where construction is unfinished; the turnback section over the BDA flyover past Silk Board is also still being built.",
      evidence: "reported",
      sourceIds: ["dh-2026-08-18", "swarajya-2026-08-19"],
    },
    {
      id: "mid-2027-slip-2026",
      date: "2026-08-23",
      dateLabel: "23 August 2026",
      kind: "deadline",
      title: "Minister moves Phase 2A opening to mid-2027; full Blue Line by March 2028",
      body: "Greater Bengaluru Development Minister Krishna Byre Gowda said Phase 2A, which earlier had a December 2026 deadline, would likely open by mid-2027, and the full Blue Line (including Phase 2B to the airport) by March 2028. A week earlier he had indicated Phase 2A could open by March 2027.",
      evidence: "reported",
      sourceIds: ["hindu-2026-08-23", "swarajya-2026-08-19"],
    },
  ],
  signals: [
    {
      id: "responsible-agency",
      label: "Responsible agency",
      value: "BMRCL",
      explanation: "Named in the PIB release of the Union Cabinet approval and in every tender and contract record.",
      evidence: "verified",
      asOf: "2021-04-20",
      sourceIds: ["pib-2021-04-20"],
    },
    {
      id: "contractor",
      label: "Contractor",
      value: "Afcons (Package 1), Shankaranarayana (Package 2)",
      explanation: "BMRCL's January 2023 presentation names both civil contractors and their contract values. The Silk Board interchange walkway contract (Milan Road Buildtech LLP, ₹55.48 crore, August 2026) is named only in news reporting. Amounts actually paid were not found in the public sources reviewed.",
      evidence: "verified",
      asOf: "2026-08-19",
      sourceIds: ["bmrcl-ppt-2023-01", "swarajya-2026-08-19"],
    },
    {
      id: "accepted-cost",
      label: "Accepted cost",
      value: "₹14,788 Cr for 2A + 2B; 2A alone not published",
      explanation: "PIB release of the April 2021 Cabinet decision. The 2016 DPR estimated ₹4,202 crore for the ORR corridor alone, and 2019 reporting cited a revised corridor estimate of about ₹5,300 crore. No revised Phase 2A estimate after 2021 was found in the public sources reviewed. The Indian Express reported a ₹40,425 crore revised cost for Phase 2 in May 2025, and discussed Phases 2A and 2B separately.",
      evidence: "verified",
      asOf: "2021-04-20",
      sourceIds: ["pib-2021-04-20", "toi-2019-12-20", "ie-2025-05-22"],
    },
    {
      id: "litigation",
      label: "Litigation",
      value: "No stay found",
      explanation: "The disposed writ near KR Puram is documented in the court record on Indian Kanoon; it was resolved by consent and did not stay the project. The December 2021 tree order is documented in news reporting of the court's order. No pending stay or injunction against Phase 2A was found in the public sources reviewed.",
      evidence: "reported",
      asOf: "2023-07-14",
      sourceIds: ["ik-royal-heritage-2023", "swarajya-2021-12-25"],
    },
    {
      id: "funding",
      label: "Funding",
      value: "ADB and JICA loans; 60% debt",
      explanation: "Reported by The Hindu at Cabinet approval and sanction time; BMRCL's presentation confirms ADB financing of both civil packages.",
      evidence: "reported",
      asOf: "2021-06-08",
      sourceIds: ["hindu-2021-04-20", "hindu-2021-06-08"],
    },
    {
      id: "next-opening",
      label: "Next opening target",
      value: "Mid-2027",
      explanation: "Minister Krishna Byre Gowda's statement of 22-23 Aug 2026; a week earlier he had indicated March 2027 for Phase 2A, so treat the month as approximate.",
      evidence: "reported",
      asOf: "2026-08-23",
      sourceIds: ["hindu-2026-08-23"],
    },
  ],
  sources: [
    {
      id: "pib-2021-04-20",
      title: "Cabinet approves Bangalore Metro Rail Project Phase 2A and Phase 2B",
      publisher: "Press Information Bureau, Ministry of Housing & Urban Affairs",
      url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1712861",
      publishedOn: "2021-04-20",
      kind: "official",
    },
    {
      id: "toi-2019-12-20",
      title: "BMRCL floats tenders for Silk Board-KR Puram, ORR commuters hope for early relief",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/bengaluru-bmrcl-floats-tenders-for-silk-board-kr-puram-orr-commuters-hope-for-early-relief/articleshow/72908567.cms",
      publishedOn: "2019-12-20",
      kind: "news",
    },
    {
      id: "tmg-2020-10-13",
      title: "Afcons & Shankaranarayana Win Bangalore Metro Phase 2A ORR Work",
      publisher: "The Metro Rail Guy",
      url: "https://themetrorailguy.com/2020/10/13/afcons-shankaranarayana-win-bangalore-metro-phase-2a-orr-work/",
      publishedOn: "2020-10-13",
      kind: "news",
    },
    {
      id: "hindu-2021-04-20",
      title: "Union Cabinet approves Bangalore Metro Rail Project phase 2A, 2B",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/cabinet-approves-bangalore-metro-rail-project-phase-2a-2b/article34367011.ece",
      publishedOn: "2021-04-20",
      kind: "news",
    },
    {
      id: "mrn-2021-05-26",
      title: "Bangalore Metro awarded Phase-2A work to Afcons and Shankaranarayana",
      publisher: "Metro Rail News",
      url: "https://metrorailnews.in/bangalore-metro-awarded-phase-2a-work-to-afcons-and-shankaranarayana/",
      publishedOn: "2021-05-26",
      kind: "news",
    },
    {
      id: "hindu-2021-06-08",
      title: "Central government issues sanction order for 58-km ORR-airport metro line",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/central-government-issues-sanction-order-for-58-km-orr-airport-metro-line/article34756163.ece",
      publishedOn: "2021-06-08",
      kind: "news",
    },
    {
      id: "swarajya-2021-12-25",
      title: "ORR Metro: Bangalore Metro secures Karnataka HC nod to axe 577 trees, translocate 212 trees between Silk Board and Kadubeesanahalli",
      publisher: "Swarajya",
      url: "https://swarajyamag.com/news-brief/orr-metro-bangalore-metro-secures-karnataka-hc-nod-to-axe-577-trees-translocate-212-trees-between-silk-board-and-kadubeesanahalli",
      publishedOn: "2021-12-25",
      kind: "news",
    },
    {
      id: "bmrcl-ppt-2023-01",
      title: "Bangalore Metro Rail Project - PH-2A (BMRCL presentation, 10 Jan 2023)",
      publisher: "BMRCL, hosted by ORRCA",
      url: "https://www.orrca.org.in/wp-content/uploads/2023/01/PPT-PH2A-BMRCL-100123.pdf",
      publishedOn: "2023-01-10",
      kind: "official",
    },
    {
      id: "ik-royal-heritage-2023",
      title: "Royal Heritage Apartment vs Bangalore Metro Rail Corporation (WP 16862/2021 c/w WP 490/2023), Karnataka High Court",
      publisher: "Indian Kanoon",
      url: "https://indiankanoon.org/doc/91450882/",
      publishedOn: "2023-07-14",
      kind: "court",
    },
    {
      id: "blrpost-2025-10-02",
      title: "ORR Metro Phase-2A to open in December 2026; IT commuters face another year's wait",
      publisher: "BLR POST",
      url: "https://blrpost.com/orr-metro-phase-2a-to-open-in-december-2026-it-commuters-face-another-years-wait/",
      publishedOn: "2025-10-02",
      kind: "news",
    },
    {
      id: "ie-2025-05-22",
      title: "Karnataka cabinet approves revised cost of Rs 40,425 crore for Bengaluru Metro phase 2, seeks central nod",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/karnataka-cabinet-revised-cost-bengaluru-metro-phase-2-central-nod-10022671/",
      publishedOn: "2025-05-22",
      kind: "news",
    },
    {
      id: "ie-2026-08-05",
      title: "Work on Bengaluru Metro's airport line 72% over, will meet 2027 deadline: BMRCL",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/bengaluru-metro-blue-line-airport-timeline-update-72-percent-progress-10818849/",
      publishedOn: "2026-08-05",
      kind: "news",
    },
    {
      id: "dh-2026-08-18",
      title: "Namma Metro Phase 2A trials from October; work on two stations on Silk Board junction-KR Puram line still incomplete",
      publisher: "Deccan Herald",
      url: "https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-namma-metro-phase-2a-trials-from-october-work-on-two-stations-on-silk-board-junction-kr-puram-line-still-incomplete-4116089",
      publishedOn: "2026-08-18",
      kind: "news",
    },
    {
      id: "swarajya-2026-08-19",
      title: "Bengaluru Metro Phase 2A to begin October trials, Silk Board link may come later",
      publisher: "Swarajya",
      url: "https://swarajyamag.com/news-brief/bengaluru-metro-phase-2a-to-begin-october-trials-silk-board-link-may-come-later",
      publishedOn: "2026-08-19",
      kind: "news",
    },
    {
      id: "hindu-2026-08-23",
      title: "Blue Line to open in phases from mid-2027; full stretch by March 2028, says KBG",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/blue-line-to-open-in-phases-from-mid-2027-full-stretch-by-march-2028-says-kbg/article71378865.ece",
      publishedOn: "2026-08-23",
      kind: "news",
    },
  ],
  suggestedQuestions: [
    "What is Phase 2A's own sanctioned and current cost?",
    "When will trains stop at Marathahalli and Silk Board stations?",
    "What extensions or delay penalties apply to the two civil contracts?",
  ],
}
