import type { CivicProject } from "../civic-projects.ts"

export const peripheralRingRoadBengaluruBusinessCorridor: CivicProject = {
  slug: "peripheral-ring-road-bengaluru-business-corridor",
  cityId: "bengaluru",
  title: "Peripheral Ring Road (Bengaluru Business Corridor)",
  shortTitle: "PRR / Business Corridor",
  routeName: "Tumakuru Road to Hosur Road",
  projectType: "Access-controlled expressway",
  road: "Peripheral Ring Road",
  status: "Delayed",
  statusNote: "Only Package 1 of the first phase has a contractor; in June 2026 BBCL's chairman said the work order would be issued within two days. The other first-phase packages still lack most of their land, and the second phase was final-notified only in September 2026.",
  ownerAgency: "Bangalore Development Authority (BDA), through Bengaluru Business Corridor Ltd",
  ownerAgencyShort: "BDA",
  nextTarget: "2029",
  wardSignalNote: "BDA · cost figures conflict (₹17,000–27,000 Cr) · most land not yet acquired",
  affectedWards: [
    { corporationId: 3, corporation: "East", wardNo: 1, name: "K Narayanapura" },
    { corporationId: 3, corporation: "East", wardNo: 28, name: "Byrathi" },
    { corporationId: 3, corporation: "East", wardNo: 31, name: "Kadugodi" },
    { corporationId: 3, corporation: "East", wardNo: 32, name: "Channasandra" },
    { corporationId: 3, corporation: "East", wardNo: 39, name: "Hagaduru" },
    { corporationId: 3, corporation: "East", wardNo: 40, name: "Varthur" },
    { corporationId: 3, corporation: "East", wardNo: 50, name: "Gunjur" },
    { corporationId: 2, corporation: "North", wardNo: 2, name: "Aerocity" },
    { corporationId: 2, corporation: "North", wardNo: 3, name: "Chowdeshwari ward" },
    { corporationId: 2, corporation: "North", wardNo: 20, name: "Sampigehalli" },
    { corporationId: 2, corporation: "North", wardNo: 21, name: "Kogilu" },
    { corporationId: 4, corporation: "South", wardNo: 34, name: "Chikkathoguru" },
  ],
  wardBasis: "Wards within 50 m of the alignment traced from OpenCity's October 2023 PRR alignment map, as mapped in OpenStreetMap (checked 17 September 2026). Kaun derived this list; the agency does not publish one. About 59 km of that alignment lies outside GBA wards.",
  aliases: [
    "PRR",
    "PRR-1",
    "PRR-2",
    "BBC",
    "Bengaluru Business Corridor",
    "BBCL",
    "ring road",
    "Shankaranarayana Constructions",
  ],
  summary: "The Peripheral Ring Road, rebranded the Bengaluru Business Corridor and now described as 117 km, was first notified in 2005. Its record since includes land acquisition disputes, Supreme Court and High Court litigation, and a quashed environmental clearance. Package 1 (Madavara to Ballari Road) got a contractor in June 2026, against a latest government deadline of 2029. Public figures conflict on the total cost (₹27,000 crore or ₹17,000 crore), on the number and length of packages, and on tree loss. No public record reviewed establishes the original completion date or the outcome of the High Court petitions that officials expected to be decided by mid-2026.",
  latestAsOf: "2026-09-16",
  alert: "Landowners say BDA's August 2026 notifications, which state that possession of PRR-1 land was taken in February 2011, breach High Court orders and contradict the state government's 2021 affidavit to the Supreme Court that only 3 acres 21 guntas of 1,810 acres had been taken.",
  metrics: [
    {
      label: "Estimated cost",
      value: "₹17,000–27,000 Cr",
      note: "The cabinet pegged the project at ₹27,000 crore in September 2024. After the October 2025 cabinet meeting, Deputy CM D.K. Shivakumar told reporters it would fall to ₹17,000 crore; June 2026 reporting still cites about ₹27,000 crore. The 2016 approval was ₹11,950 crore.",
      evidence: "conflicting",
    },
    {
      label: "Land possessed by 2021",
      value: "3 of 1,810 acres",
      note: "The state government's affidavit of 9 November 2021 to the Supreme Court, quoted in the Karnataka High Court's December 2024 judgment: 3 acres 21 guntas of 1,810 acres 18.5 guntas.",
      evidence: "verified",
    },
    {
      label: "Package 1 land",
      value: "78%",
      note: "523 of 665 acres as of May 2026, reported from BBCL's chairman. Package 2 had 123 of about 433 acres; Package 3 had 26 of about 710.",
      evidence: "reported",
    },
    {
      label: "Package 1 contract",
      value: "~₹3,500 Cr",
      note: "Letter of Acceptance to Shankaranarayana Constructions in June 2026, including maintenance, as reported. The package length is reported as anywhere from 19.5 to 23 km.",
      evidence: "reported",
    },
  ],
  records: [
    {
      id: "pn-2005-part1",
      date: "2005-09-23",
      dateLabel: "23 September 2005",
      kind: "start",
      title: "Preliminary notification for PRR Part 1 land",
      body: "BDA issued preliminary notification No. BDA/Commr/DC(LA)/SALAO/79/2005-06 for 1,962 acres 26 guntas of land for PRR Part 1, as recited in the Karnataka High Court's December 2024 Byrappa judgment.",
      evidence: "verified",
      sourceIds: ["hc-2024-byrappa"],
    },
    {
      id: "pn-2005-part2",
      date: "2005-12-12",
      dateLabel: "12 December 2005",
      kind: "start",
      title: "Preliminary notification for PRR Part II land acquisition",
      body: "BDA issued preliminary notification No. BDA/COMMR/DC(LA)/SALAO/115/2005-06 for PRR Part II land (Hosur Road–Mysuru Road–Tumakuru Road), as recited in the Karnataka High Court's December 2024 Byrappa judgment. Citizen Matters reports that plots of nearly 14,000 families were notified between 2005 and 2010.",
      evidence: "verified",
      sourceIds: ["hc-2024-byrappa", "cm-2026-02-04"],
    },
    {
      id: "bda-proposal-2006",
      date: "2006-11-27",
      dateLabel: "27 November 2006",
      kind: "start",
      title: "BDA proposes a 116-km Peripheral Ring Road",
      body: "BDA proposed a peripheral ring road encircling Bangalore for 116 km in its letter to the state government, as recorded in the Supreme Court's January 2022 order.",
      evidence: "verified",
      sourceIds: ["sc-2022-bda-karnataka"],
    },
    {
      id: "scheme-sanction-2007",
      date: "2007-04-23",
      dateLabel: "23 April 2007",
      kind: "start",
      title: "State government sanctions the PRR scheme",
      body: "The Government of Karnataka sanctioned the PRR scheme vide order UDD 399 MNX 2006, as recorded in the Supreme Court's January 2022 order. No public source reviewed states the completion deadline set at sanction; that is an evidence gap.",
      evidence: "verified",
      sourceIds: ["sc-2022-bda-karnataka"],
    },
    {
      id: "final-notification-2007",
      date: "2007-06-29",
      dateLabel: "29 June 2007",
      kind: "land",
      title: "Final notification to acquire 1,810 acres 18.5 guntas",
      body: "Government issued the final notification under Section 19(1) of the BDA Act to acquire 1,810 acres 18.5 guntas for the PRR. The Supreme Court's 2020 judgment treats this date as the commencement of the PRR project.",
      evidence: "verified",
      sourceIds: ["go-udd-214-2019", "sc-2020-bda-hegde"],
    },
    {
      id: "hc-quash-2011",
      date: "2011-09-08",
      dateLabel: "8 September 2011",
      kind: "court",
      title: "High Court quashes PRR notifications in entirety",
      body: "A batch of writ petitions (WP 21920-21922/2011, Smt. A. Gowramma and others) was allowed by the Karnataka High Court, quashing the PRR notifications in their entirety, as recited in the December 2024 Byrappa judgment.",
      evidence: "verified",
      sourceIds: ["hc-2024-byrappa"],
    },
    {
      id: "hc-hegde-2014",
      date: "2014-07-22",
      dateLabel: "22 July 2014",
      kind: "court",
      title: "High Court: acquisition not lapsed, but compensation under 2013 Act",
      body: "A Single Judge deciding WP 4550/2008 (Sudhakar Hegde) and connected petitions held the PRR acquisition had not lapsed under Section 24 of the 2013 land acquisition Act, but that compensation must be determined under the 2013 Act since no award had been passed. BDA said this upset the project's budget calculations and moved the Supreme Court.",
      evidence: "verified",
      sourceIds: ["sc-2022-bda-karnataka"],
    },
    {
      id: "go-cost-2016",
      date: "2016-07-11",
      dateLabel: "11 July 2016",
      kind: "cost",
      title: "Government approves PRR at ₹11,950 crore",
      body: "Government Order UDD 345 MNJ 2013 approved implementing the PRR at an estimated ₹11,950 crore: ₹8,100 crore for land acquisition and ₹3,850 crore for construction including an Intelligent Transport System, with an SPV to execute it.",
      evidence: "verified",
      sourceIds: ["go-udd-214-2019"],
    },
    {
      id: "ngt-quashes-ec-2019",
      date: "2019-02-08",
      dateLabel: "8 February 2019",
      kind: "court",
      title: "NGT quashes the project's environmental clearance",
      body: "The National Green Tribunal's Principal Bench quashed the environmental clearance for the 8-lane, 65-km Tumakuru Road-Hosur Road PRR because the EIA's primary data was more than three years old, freezing the project.",
      evidence: "verified",
      sourceIds: ["sc-2020-bda-hegde", "nie-2020-03-18"],
    },
    {
      id: "go-udd-214-2019",
      date: "2019-10-03",
      dateLabel: "3 October 2019",
      kind: "scope",
      title: "Government Order widens PRR to 100 m and sets funding plan",
      body: "GO UDD 214 MNJ 2018 approved construction with a 100 m right of way (up from 75 m), compensation in cash/TDR by 2017-18 market rates, tenders in packages only after the SPV takes possession of 80% of the land, and JICA loan assistance for construction with land costs met by state loans.",
      evidence: "verified",
      sourceIds: ["go-udd-214-2019"],
    },
    {
      id: "sc-eco-2020",
      date: "2020-03-17",
      dateLabel: "17 March 2020",
      kind: "court",
      title: "Supreme Court faults BDA's environmental assessment, orders fresh EIA",
      body: "In BDA v Sudhakar Hegde (Civil Appeal 2566/2019), the Supreme Court, invoking Article 142, noted BDA's 'abject failure' to state correct tree figures (BDA claimed 519; the Deputy Conservator of Forests counted 16,785) and undisclosed forest land at Jarakabande Kaval, and directed BDA to hire a sector-specific accredited EIA consultant and obtain environmental certification afresh, with no damage to petroleum pipelines on the alignment.",
      evidence: "verified",
      sourceIds: ["sc-2020-bda-hegde", "nie-2020-03-18"],
    },
    {
      id: "sc-section24-2022",
      date: "2022-01-20",
      dateLabel: "20 January 2022",
      kind: "court",
      title: "Supreme Court: 2013 land Act does not apply to BDA acquisitions",
      body: "In BDA v State of Karnataka, the Supreme Court held that the Land Acquisition Act, 1894, stands incorporated into the BDA Act, so the 2013 Act (including its lapse and higher-compensation provisions) does not govern PRR acquisitions, overruling the 2014 single-judge judgment.",
      evidence: "verified",
      sourceIds: ["sc-2022-bda-karnataka"],
    },
    {
      id: "cabinet-27000cr-2024",
      date: "2024-09-05",
      dateLabel: "5 September 2024",
      kind: "cost",
      title: "Cabinet pegs PRR cost at ₹27,000 crore with 75% loan funding",
      body: "The Karnataka Cabinet approved the implementing agencies raising loans for the ₹27,000-crore project, with the state as guarantor and 75% of cost as loans, and agreed to compensation under the 2013 Act with a TDR option for volunteers. It also decided to appoint a non-minister chairman for the SPV, Bengaluru Business Corridor Ltd.",
      evidence: "reported",
      sourceIds: ["ie-2024-09-05"],
    },
    {
      id: "hc-byrappa-2024",
      date: "2024-12-20",
      dateLabel: "20 December 2024",
      kind: "court",
      title: "High Court refuses to quash Part II acquisition; orders compensation and road completion",
      body: "Justice E.S. Indiresh, disposing of the Byrappa batch (WP 61154/2014 with five others) over PRR Part II, refused to quash the acquisition of about 31 acres where no award had been passed since the 2005-06 preliminary and 2011 final notifications. He directed BDA to pass awards, pay compensation within six months, take possession, and complete the remaining 1.8 km of the 10.3 km road (8.5 km was already built). The judgment quotes the state government's affidavit of 9 November 2021 to the Supreme Court: of 1,810 acres 18.5 guntas notified, possession had been taken of only 3 acres 21 guntas.",
      evidence: "verified",
      sourceIds: ["hc-2024-byrappa", "hindu-2025-01-08"],
    },
    {
      id: "cabinet-bbc-2025",
      date: "2025-10-16",
      dateLabel: "16 October 2025",
      kind: "scope",
      title: "Cabinet approves 117-km tolled Bengaluru Business Corridor; width cut to 65 m, cost to ₹17,000 crore",
      body: "The Cabinet approved the 117-km tolled BBC (formerly PRR) connecting Electronic City with Tumakuru and Mysuru roads. Deputy CM D.K. Shivakumar said the earlier ₹27,000 crore estimate would drop to ₹17,000 crore, the road width would be 65 m instead of 100 m with 35 m of developed commercial land for land losers, and compensation would be two times guidance value in urban stretches and three times in rural ones; he said the corridor would be completed in two years and that 1,900 families would be affected.",
      evidence: "reported",
      sourceIds: ["hindu-2025-10-16"],
    },
    {
      id: "dks-deadline-2026",
      date: "2026-02-06",
      dateLabel: "6 February 2026",
      kind: "deadline",
      title: "Deputy CM: BBC-1 will be completed in a year and a half",
      body: "D.K. Shivakumar said BBC-1 (earlier PRR) would be completed in a year and a half and that 650 landowners had agreed to part with land, with compensation paid to 400.",
      evidence: "reported",
      sourceIds: ["hindu-2026-02-06"],
    },
    {
      id: "deadline-2029",
      date: "2026-03-24",
      dateLabel: "March 2026",
      kind: "deadline",
      title: "Government sets 2029 as new completion deadline",
      body: "The state government set 2029 as the new completion deadline for the 73-km PRR-1 corridor, to be financed by a HUDCO loan, per The Times of India. The Deputy CM had earlier said the corridor would be complete in two years (October 2025) and in a year and a half (February 2026).",
      evidence: "reported",
      sourceIds: ["toi-2026-03-24", "hindu-2025-10-16", "hindu-2026-02-06"],
    },
    {
      id: "ec-april-2026",
      date: "2026-04-27",
      dateLabel: "27 April 2026",
      kind: "accountability",
      title: "MoEFCC grants environmental clearance",
      body: "The Ministry of Environment, Forest and Climate Change granted environmental clearance to the PRR/BBC on 27 April 2026, per Deccan Herald and other outlets. TOI separately reported that the PRR 'obtained the environmental clearance only in 2023'; whether the 2026 clearance covers a revised scope or a distinct phase is not resolved in the public sources reviewed. The original clearance was quashed by the NGT in 2019 and the Supreme Court ordered a fresh EIA in 2020.",
      evidence: "conflicting",
      sourceIds: ["dh-2026-05-01", "toi-2026-03-24", "sc-2020-bda-hegde"],
    },
    {
      id: "land-78pct-2026",
      date: "2026-05-13",
      dateLabel: "13 May 2026",
      kind: "land",
      title: "Package 1 land acquisition crosses 78%; packages 2 and 3 far behind",
      body: "BBC Ltd chairman L.K. Atheeq said 523 of 665 acres for Package 1 (Tumakuru Road-Ballari Road) had been taken, against a government condition of 80% before work orders; Package 2 (Ballari Road-Whitefield Junction) had 123 of 433 acres and Package 3 (Whitefield Junction-Electronics City) only 26 of 710 acres. Officials said clubbed High Court petitions challenging PRR Phase-1 acquisition were expected to be decided by June-July 2026; no verdict is found in the public sources reviewed as of 16 September 2026.",
      evidence: "reported",
      sourceIds: ["hindu-2026-05-13", "fe-2026-05-18"],
    },
    {
      id: "snc-l1-2026",
      date: "2026-05-21",
      dateLabel: "21 May 2026",
      kind: "cost",
      title: "Financial bids opened; Shankaranarayana Constructions lowest for Package 1",
      body: "BBC chairman L.K. Atheeq announced that financial bids for the first 19.5-km stretch were opened and Bengaluru-based Shankaranarayana Constructions (SNC) emerged L1; award was contingent on pending High Court petitions over land acquisition.",
      evidence: "reported",
      sourceIds: ["dh-2026-05-21"],
    },
    {
      id: "loa-snc-2026",
      date: "2026-06-13",
      dateLabel: "13 June 2026",
      kind: "cost",
      title: "Letter of Acceptance issued to SNC for Package 1 at about ₹3,500 crore",
      body: "SNC received the LoA for Package 1, a 21-km Madavara-Ballari Road stretch with three cloverleaf interchanges, a grade separator, two rail overbridges, about 7.5 km of elevated corridor and a 12-lane carriageway, having quoted 4.9% above estimate (about ₹3,500 crore including maintenance). The LoA itself is not publicly posted; naming rests on attributed reporting of BDA/BBCL's announcement. The Hindu's report put the overall project estimate at about ₹27,000 crore, of which nearly ₹21,000 crore for land acquisition — conflicting with the ₹17,000 crore figure given after the October 2025 cabinet.",
      evidence: "reported",
      sourceIds: ["hindu-2026-06-13", "dh-2026-05-21"],
    },
    {
      id: "work-order-2026",
      date: "2026-06-24",
      dateLabel: "24 June 2026",
      kind: "start",
      title: "Work order for Package 1 to be issued",
      body: "BBCL's chairman said the contractor had submitted its performance bank guarantee and the engineering section had been directed to sign the agreement and issue the work order within two days. A final notification was also issued for land to integrate the project with the NICE corridor at Madavara village. The work order's issue date and construction period were not found in the public sources reviewed.",
      evidence: "reported",
      sourceIds: ["hindu-2026-06-24"],
    },
    {
      id: "possession-row-2026",
      date: "2026-08-27",
      dateLabel: "27 August 2026",
      kind: "accountability",
      title: "Landowners say BDA's August 2026 possession notifications violate High Court orders and contradict its Supreme Court affidavit",
      body: "PRR-1 landowners said BDA's 18 August 2026 Gazette notifications, which state that possession of their land was taken in February 2011, violate High Court interim and status-quo orders. They cited the 2021 affidavit to the Supreme Court recording that compensation had been paid in only three cases and possession taken of 3 acres 21 guntas of 1,810 acres 18.5 guntas. The PRR farmers' association said it would petition the government to withdraw or suspend the notifications.",
      evidence: "reported",
      sourceIds: ["nie-2026-08-27", "hc-2024-byrappa"],
    },
    {
      id: "final-notification-prr2-2026",
      date: "2026-09-08",
      dateLabel: "8 September 2026",
      kind: "land",
      title: "Final notification to acquire 1,427 acres for PRR-2",
      body: "BDA issued the final notification to acquire 1,427 acres 24.25 guntas for PRR-2 (52.63 km), covering six hoblis — Attibele, Jigani, Begur, Uttarahalli, Kengeri and Dasanapura — across 31 villages, connecting Hosur Road-Mysuru Road (33.45 km) and Magadi Road-Tumakuru Road (8.4 km) via the S.M. Krishna Road through Nadaprabhu Kempegowda Layout. About 40 acres remain under litigation, and tenders for PRR-1 packages 2-4 are yet to be floated.",
      evidence: "reported",
      sourceIds: ["hindu-2026-09-08"],
    },
  ],
  signals: [
    {
      id: "agency",
      label: "Responsible agency",
      value: "BDA, through BBCL",
      explanation: "BDA is the implementing agency per the October 2025 cabinet decision; execution sits with Bengaluru Business Corridor Ltd, the SPV (a predecessor SPV, Bengaluru PRR Development Corporation Ltd, was incorporated on 9 October 2017 under the 2016 Government Order).",
      evidence: "verified",
      asOf: "2026-09-16",
      sourceIds: ["hindu-2025-10-16", "go-udd-214-2019", "hindu-2026-05-13"],
    },
    {
      id: "contractor",
      label: "Contractor",
      value: "Shankaranarayana Constructions (Package 1 only)",
      explanation: "SNC received the Letter of Acceptance for Package 1 in June 2026 after emerging lowest bidder. The letter is not publicly posted, so the naming rests on attributed reporting of BBCL's announcement. Tenders for the remaining PRR-1 packages had not been floated as of 8 September 2026; reports describe the first phase as three or four packages in all.",
      evidence: "reported",
      asOf: "2026-09-08",
      sourceIds: ["hindu-2026-06-13", "dh-2026-05-21", "hindu-2026-09-08"],
    },
    {
      id: "accepted-cost",
      label: "Accepted cost",
      value: "₹27,000 Cr or ₹17,000 Cr",
      explanation: "The September 2024 cabinet pegged the project at ₹27,000 crore. After the October 2025 cabinet meeting, Deputy CM D.K. Shivakumar told reporters it would fall to ₹17,000 crore through redesigned compensation. The Hindu's June 2026 report still cites about ₹27,000 crore overall (₹21,000 crore for land). No reconciled official figure was found in the public sources reviewed.",
      evidence: "conflicting",
      asOf: "2026-06-13",
      sourceIds: ["ie-2024-09-05", "hindu-2025-10-16", "hindu-2026-06-13"],
    },
    {
      id: "litigation",
      label: "Litigation",
      value: "Phase 1 acquisition petitions; verdict not public",
      explanation: "Petitions challenging PRR Phase-1 land acquisition were clubbed before the Karnataka High Court with arguments drawing to a close in May 2026 and a judgment expected by June-July 2026 per officials; no verdict is found in the public sources reviewed as of 16 September 2026. Separately, landowners allege BDA's 18 August 2026 possession notifications violate HC status-quo orders, and about 40 acres of PRR-2 land remains under litigation.",
      evidence: "reported",
      asOf: "2026-09-08",
      sourceIds: ["hindu-2026-05-13", "dh-2026-05-21", "nie-2026-08-27", "hindu-2026-09-08"],
    },
    {
      id: "environment",
      label: "Environmental clearance",
      value: "Clearance reported April 2026; scope unclear",
      explanation: "The original EC was quashed by the NGT in February 2019 and the Supreme Court ordered a fresh EIA in March 2020. TOI reported the PRR obtained EC in 2023, while Deccan Herald and other outlets reported MoEFCC granted clearance on 27 April 2026; which instrument the 2026 clearance covers is not resolved in the public sources reviewed. The alignment still requires diversion of 2.4 hectares of Jarakabande Kaval reserve forest (700 m stretch), which BDA had not formally sought as of November 2025.",
      evidence: "conflicting",
      asOf: "2026-05-01",
      sourceIds: ["dh-2026-05-01", "toi-2026-03-24", "sc-2020-bda-hegde", "toi-2025-11-15"],
    },
    {
      id: "deadline",
      label: "Latest completion target",
      value: "2029",
      explanation: "The government set 2029 as the new deadline in March 2026, per The Times of India. The Deputy CM had earlier said two years (October 2025) and a year and a half (February 2026). No original completion date from the 2007 sanction was found in the public sources reviewed.",
      evidence: "reported",
      asOf: "2026-03-24",
      sourceIds: ["toi-2026-03-24", "hindu-2025-10-16", "hindu-2026-02-06"],
    },
  ],
  sources: [
    {
      id: "go-udd-214-2019",
      title: "Government Order No. UDD 214 MNJ 2018, dated 03.10.2019: approval for construction of the Peripheral Ring Road with modifications",
      publisher: "Government of Karnataka (hosted on forestsclearance.nic.in)",
      url: "https://forestsclearance.nic.in/DownloadPdfFile.aspx?FileName=0_0_8111312481271bdake.pdf&FilePath=..%2Fwritereaddata%2FAddinfo%2F",
      publishedOn: "2019-10-03",
      kind: "official",
    },
    {
      id: "sc-2022-bda-karnataka",
      title: "Bangalore Development Authority & Anr. v. State of Karnataka & Ors., order dated 20 January 2022 (2022 LiveLaw (SC) 76)",
      publisher: "Supreme Court of India (PDF via LiveLaw)",
      url: "https://www.livelaw.in/pdf_upload/76-bangalore-devel-authority-v-state-of-karnataka-20-jan-2022-415701.pdf",
      publishedOn: "2022-01-20",
      kind: "court",
    },
    {
      id: "sc-2020-bda-hegde",
      title: "Bengaluru Development Authority v. Mr Sudhakar Hegde & Ors., Civil Appeal No. 2566 of 2019, judgment dated 17 March 2020",
      publisher: "Supreme Court of India",
      url: "https://api.sci.gov.in/supremecourt/2019/8100/8100_2019_3_1503_21539_Judgement_17-Mar-2020.pdf",
      publishedOn: "2020-03-17",
      kind: "court",
    },
    {
      id: "hc-2024-byrappa",
      title: "Sri. C. Byrappa vs The State Of Karnataka, WP 61154/2014 c/w others, Karnataka High Court, 20 December 2024",
      publisher: "Karnataka High Court (via Indian Kanoon)",
      url: "https://indiankanoon.org/doc/118012548/",
      publishedOn: "2024-12-20",
      kind: "court",
    },
    {
      id: "hindu-2026-09-08",
      title: "BDA issues final notification to acquire 1,427 acres for Peripheral Ring Road-2",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/bda-issues-final-notification-to-acquire-1427-acres-for-peripheral-ring-road-2/article71442185.ece",
      publishedOn: "2026-09-08",
      kind: "news",
    },
    {
      id: "hindu-2026-06-24",
      title: "Work for PRR likely to begin soon as formalities gather pace",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/work-for-prr-likely-to-begin-soon-as-formalities-gather-pace/article71142076.ece",
      publishedOn: "2026-06-24",
      kind: "news",
    },
    {
      id: "hindu-2026-06-13",
      title: "PRR gains momentum, Bengaluru-based SNC gets letter of acceptance for package-1",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/prr-gains-momentum-bengaluru-based-snc-gets-letter-of-acceptance-for-package-1/article71097628.ece",
      publishedOn: "2026-06-13",
      kind: "news",
    },
    {
      id: "hindu-2026-05-13",
      title: "Nearly 80% land acquisition done for PRR Package 1 in Bengaluru, work order to be issued in June",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/national/karnataka/bengaluru-nearly-80-land-acquisition-done-for-prr-package-1-work-order-to-be-issued-in-june/article70969734.ece",
      publishedOn: "2026-05-13",
      kind: "news",
    },
    {
      id: "hindu-2026-02-06",
      title: "BBC-1 to be completed over next year and a half: DKS",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/national/karnataka/bbc-1-to-be-completed-over-next-year-and-a-half-dks/article70596569.ece",
      publishedOn: "2026-02-06",
      kind: "news",
    },
    {
      id: "hindu-2025-10-16",
      title: "Karnataka Cabinet approves Bengaluru Business Corridor to connect Electronic City with Mysuru, Tumakuru roads",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/national/karnataka/karnataka-cabinet-approves-bengaluru-business-corridor-to-connect-electronic-city-with-mysuru-tumakuru-roads/article70171630.ece",
      publishedOn: "2025-10-16",
      kind: "news",
    },
    {
      id: "hindu-2025-01-08",
      title: "Karnataka HC directs BDA to complete remaining 1.8 km road of PRR Part II project while refusing to quash acquisition of 31 acres of land",
      publisher: "The Hindu",
      url: "https://www.thehindu.com/news/cities/bangalore/karnataka-hc-directs-bda-to-complete-remaining-18-km-road-of-prr-part-ii-project-while-refusing-to-quash-acquisition-of-31-acres-of-land/article69077218.ece",
      publishedOn: "2025-01-08",
      kind: "news",
    },
    {
      id: "ie-2024-09-05",
      title: "Karnataka Cabinet pegs Peripheral Ring Road cost at Rs 27,000 crore; extends deadline for One Time Settlement scheme",
      publisher: "The Indian Express",
      url: "https://indianexpress.com/article/cities/bangalore/karnataka-cabinet-peripheral-ring-road-deadline-one-time-settlement-scheme-9552565/",
      publishedOn: "2024-09-05",
      kind: "news",
    },
    {
      id: "toi-2026-03-24",
      title: "PRR rebooted: 2029 deadline revives stalled Bengaluru Business Corridor project",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/prr-rebooted-2029-deadline-revives-stalled-bengaluru-business-corridor-project/articleshow/129784189.cms",
      publishedOn: "2026-03-24",
      kind: "news",
    },
    {
      id: "toi-2025-11-15",
      title: "Bengaluru's Peripheral Ring Road to cut through 700 metres of reserve forest",
      publisher: "The Times of India",
      url: "https://timesofindia.indiatimes.com/city/bengaluru/bengalurus-peripheral-ring-road-to-cut-through-700-metres-of-reserve-forest/articleshow/125353990.cms",
      publishedOn: "2025-11-15",
      kind: "news",
    },
    {
      id: "dh-2026-05-21",
      title: "SNC emerges as lowest bidder for first 19.5-km stretch of Bengaluru Business Corridor",
      publisher: "Deccan Herald",
      url: "https://www.deccanherald.com/india/karnataka/bengaluru/snc-emerges-as-lowest-bidder-for-first-19-5-km-stretch-of-bengaluru-business-corridor-4011917",
      publishedOn: "2026-05-21",
      kind: "news",
    },
    {
      id: "dh-2026-05-01",
      title: "Bengaluru's peripheral ring road project gets environmental clearance",
      publisher: "Deccan Herald",
      url: "https://www.deccanherald.com/india/karnataka/bengaluru/bengalurus-peripheral-ring-road-project-gets-environmental-clearance-3988102",
      publishedOn: "2026-05-01",
      kind: "news",
    },
    {
      id: "nie-2026-08-27",
      title: "Bengaluru: PRR-1 affected landowners urge government to suspend BDA notification",
      publisher: "The New Indian Express",
      url: "https://www.newindianexpress.com/cities/bengaluru/2026/Aug/27/bengaluru-prr-1-affected-landowners-urge-govt-to-suspend-bda-notification",
      publishedOn: "2026-08-27",
      kind: "news",
    },
    {
      id: "nie-2020-03-18",
      title: "Apex court raps BDA over PRR, seeks new eco-study",
      publisher: "The New Indian Express",
      url: "https://www.newindianexpress.com/cities/bengaluru/2020/Mar/18/apex-court-raps-bda-over-prr-seeks-new-eco-study-2118183.html",
      publishedOn: "2020-03-18",
      kind: "news",
    },
    {
      id: "fe-2026-05-18",
      title: "Bengaluru's 20-year delayed Peripheral Ring Road project finally moves toward execution",
      publisher: "The Financial Express",
      url: "https://www.financialexpress.com/business/roadways-bengalurus-20-year-delayed-peripheral-ring-road-finally-moves-toward-execution-4243937/",
      publishedOn: "2026-05-18",
      kind: "news",
    },
    {
      id: "cm-2026-02-04",
      title: "Bengaluru's Peripheral Ring Road: Two decades on, who really benefits?",
      publisher: "Citizen Matters",
      url: "https://citizenmatters.in/bengalurus-peripheral-ring-road-two-decades-on-who-really-benefits/",
      publishedOn: "2026-02-04",
      kind: "news",
    },
  ],
  suggestedQuestions: [
    "Which PRR cost is current: ₹17,000 crore or ₹27,000 crore?",
    "How much PRR-1 land has BDA taken possession of, and when?",
    "When will PRR Packages 2 and 3 be tendered?",
  ],
}
