-- ============================================================================
-- Migration: 20260506 — Multi-city pin_lookup (superseded; intentionally a no-op)
--
-- This version is kept so migration history stays aligned with production,
-- where it must be recorded as applied (see docs/local-database.md). Its
-- original body is in git history (PR #37).
--
-- It is empty because 20260505_remote_schema.sql is a September 2026 dump of
-- the live public schema, and every later migration replays on top of that
-- snapshot during `supabase db reset`. The original body would have diverged
-- local databases from production:
--   * it swapped wards' primary key from (id) to (city_id, ward_no), whereas
--     production keeps wards_pkey PRIMARY KEY (id) plus
--     wards_city_id_ward_no_key UNIQUE (city_id, ward_no);
--   * it created wards_city_id_idx, which production does not have;
--   * it replaced pin_lookup with a version production has since superseded
--     (20260910_gba_independent_pin_lookup.sql).
--
-- Do not reintroduce schema changes here; add a new, idempotent migration.
-- ============================================================================

SELECT 1;
